### ISSUE TITLE
There is always goes down when the monitor is turned off with USB-C

### ISSUE THREAD

**Issue by daliang1215** [osy/HaC-Mini#1003]
**Describe the bug**

Whenever I turn off the monitor, instead of cutting off the power, the system goes down. The NUC power adapter must be unpluged directly and then reinserted before the system can boot。  

But  NUC is functioning normally  if I using mini-dp。

**Expected behavior**
NUC is functioning normally when the monitor is turned off

**Configuration**
- HaC Mini version [e.g: 2.0]: [v3.1.5]
- OSX version [e.g: 10.14.6]: 12.2
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]:  Crucial P1 1T , M.2, NVME
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: NULL
- First DIMM model [e.g: Patriot DDR4-2666 16GB]:  Kingston FURY 16GB DDR4 3200
- Second DIMM model (if installed): Kingston FURY 16GB DDR4 3200
- Display port(s) used [e.g: USB-C, mini DP]: USB-C to USB-C; AOC LV273HUPR 
- Display resolution(s) [e.g: 4K, 5K]: 4K
- Any TB3 devices: NULL
- Any USB devices:  connect K1 keyboard [K1 keyboard detail](https://item.jd.com/100014608888.html)
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]:  apple trackpad  

**Modifications**
NO

**Panic log**
i don't know how to find it .

**Comment by daliang1215** [comment]
> 有三种猜测。
> 
> 1. 我记得 nuc 的后置 hdmi 接口是带 cec 的，默认 bios 设置 nuc 开机时是会让电视也跟着开机的。bios 设置里也可以设置电视关机自动跟着关机，但是不清楚 miniDP 或者 USB-C 口是否有这种功能。
> 2. 如果显示器那头也是 USB-C 的话，有可能是显示器关闭时造成 USB 内短暂短路触发了主板的电路保护。
> 3. 如果刷过雷电补丁的话，USB-C 口在 USB 设备和雷电设备切换时小概率会造成系统死掉，这个是我遇到过的问题，但不是直接黑屏。

我是第二种情况。 USB-C  <- --->  USB-C . 
刷过雷电补丁，每次一关显示器必死机。我的也不是黑屏。^_^

**Comment by xiaooloong** [comment]
那应该是第三种问题。双头都是 USB-C 的话，雷电接口是工作在 USB-C DisplayPort Alternate Mode 模式的，就是和常见的“全功能 USB-C 接口”的视频输出功能一个模式，跟雷电协议没啥关系了。如果手头没有雷电设备的话，可以还原一下雷电补丁试试，应该是不影响这个接口输出视频的。

**Comment by daliang1215** [comment]
重新安装了HaCMini，雷霆部分选择了传统雷霆，卸载了原来安装的原生雷霆，问题已解决

**Comment by xiaooloong** [comment]
选择「原生雷雳」安装后，系统里会有一个叫做「Thunderbolt Patcher」的程序。这个程序是用来给雷电固件打补丁来让雷电固件工作在苹果原生雷电模式下的。如果你之前是用这个程序刷过雷电固件，你需要重新打开这个程序，勾选右下角按钮旁边的「Uninstall」进行刷写。

刷写完成后需要给 nuc 断电 10 秒雷电主控才会重新加载固件生效。

另外建议每次刷固件前也执行一次 10 秒断电的操作，然后不要在雷电口连接任何设备，接着开机进系统直接进行刷写操作。因为我发现运行久了或者刷写前连接过设备，刷固件的时候就容易跑飞，导致雷电砖掉。我曾经两次出现过这种情况，最后买了一个编程器和烧录夹救的砖：https://github.com/osy/HaC-Mini/issues/270#issuecomment-1066049732
