### ISSUE TITLE
Follow the guidelines( v3.1.5) still do not see OTA updates

### ISSUE THREAD

**Issue by jk2573963** [osy/HaC-Mini#1004]
**Describe the bug**
Follow the guidelines( v3.1.5) still do not see OTA updates

**Expected behavior**
Follow the guidelines ，I open Terminal and run sudo /System/Library/PrivateFrameworks/Seeding.framework/Versions/A/Resources/seedutil unenroll,
Terminal show:
Unenrolling...

Program: (null)
Is Enrolled: NO
Build is seed: NO
CatalogURL: (null)
NSShowFeedbackMenu: NO
DisableSeedOptOut: NO
Asset Audience: 
**Configuration**
- HaC Mini version : v3.1.5
- OSX version : 12.3.1
- NUC model :  NUC8i7HNK
- Boot SSD model and protocol : WD SN550 1TB NVMe
- Second SSD model and protocol (if installed): KIOXIA  RC10 500GB NVMe

**Comment by osy** [comment]
Secure boot is enabled and working?

**Comment by jk2573963** [comment]
Secure boot is enabled and working，I tried again and it worked.Thx bro.
