### ISSUE TITLE
Can not boot from the USB

### ISSUE THREAD

**Issue by sohail579** [osy/HaC-Mini#1006]
Hi, I have followed all the instructions and am trying to install Monterey onto my NUC.  i hold F10 to get to the boot menu and  I can see OpenCore however when i click it it does nothing but refresh the boot select screen

what am i doing wrong?

I aslo have windows 11 installed on a seperate NVME in the same system.

**Comment by ulm0** [comment]
I got a similar issue, and used verbose boot and show boot menu from within boot options, it solved the issue, hope it works for ya.
![image](https://user-images.githubusercontent.com/13160093/170109851-efeed8dc-a0df-43ca-8089-eb179c0ac6b4.png)

**Comment by sohail579** [comment]
Thanks it didn't work but then it did.  Quite strange.  Initially it did nit work.  But then it did because I tried to boot from other usb ports in the end it booted from the blue port on the front..
