### ISSUE TITLE
Unexpected error using usb installer.

### ISSUE THREAD

**Issue by ivan-ef** [osy/HaC-Mini#1023]
**Describe the bug**

Unexpected reboot using usb installer.
Boot log:
![tempImageFunvGx](https://user-images.githubusercontent.com/67600440/193467613-6ef20278-ed47-4bd3-97e3-dfe5d79b2b76.gif)

text version:

*[EB.LD.LF|IN] 0 1 ("(null string)"> ("]">
#LEB.B.SBS ISZ] 723512
#LEB1B:SHA] (966d5e3bcBa58fe6f 354f 044a21095ae05081193>
#LEB.WL.PWLFNV11] Err (®xE) (- RT.GV wake-failure 7C436110-ABZA-4BBB-ABB0-FE41995C9F8Z
#LEB.WL.DTI!] Err(BxE) <- EB.WL.PWLFNV
#LEB.WL.PWLFRTCINONE]
#[EB.WL.DI11] Err(0xE) (- EB.WL.PWLFRTC
#LEB.LD.LKCID]("System\Library\ernelCollections\BootKernelExtensions.kc.deveLopment*>
@LEB.LD.LFlIN7@4<@System)Wibrary)(KernelCollections\YBootKernelExtensilons.ks.development")y(9=72
#[EB.LD.OFS|OPEN!] Err(8xE) ("System\Wibrary\WernelCollections\\BootKernelExtensions.kc.development*>
#TEB.LD.LKCIR.21<"System\Library\KernelCollections\BootKerne(Extensions.kc">
#LEB.LD.LF|IN1 0 1 ("Systen)WLibrary\WernelCollections\\BootKernelExtensions.ke")(9*>
*[EBISB:P] 0x2
#LEB.RH.SBGMFNS|ApECID]BxBC595F742EAFF9
#LEBISB: SBGMFNS]j174ap.BC595F742EAFF9.intm
#LEBISB:MF1 Systen\Wibrary\\ernelCollections\\BootKernelExtensions.kc.j174ap.BC595F742EAFF9.infa
#LEB.LD.LF1IN] 01 ("System\WLibrary\WernelCollections\\BootKerne(Extensions.kC.j174ap.BC59SF742ERFF9.infin*>("0">
#LEB.LD.OFSIOPEN!] Err(0xE) ("System\WLibrary\WernelCollections\\BootKernelExtensions.kC.J174ap.BC595F742ERFF9.infin">
#LEB.SB.VK11] Err(BxE) (- EB.LD.LF
#LEB.LD.LKCFFP11] Err(BxiA) <- EB.SB.SBVK
#LEBICS: SRBM] secure-boot
#LEBIB:RB]
#IEBIWL] D O Ox01 0x41 24 OxOE
#[EB I REBOOT] 1
#LEBILOG:RESET:RECOVERY] 2017-01-04T20:00:57

**Environment:**
 - Installer OSX version: Monterey 12.5
 - HaC Mini installer version: 3.20

**Additional context**
1. At first boot "open core USB drive" is shown in bios. 
2. opencore Installer from USB drive doest't start. "no bootable device detected" message shown.
3. after plugging NVMe drive with same opencore installer, the installer will also boot from usb drive, but reboots every time with error descibed above.

**Comment by sunrez** [comment]
Hello,

You might have better luck using the very first release that supports Monterey and then trying to upgrade.

I ran into the exact same issue when trying to use the latest installer with Big Sur (11.7). 

What worked for me was to go back to 3.1.4 release, update the Big Sur installer, install Big Sur, install 3.1.4 to internal EFI and then after everything verified work was to switch to the latest 3.2.1 (which works fine after macOS is fully installed).

**Comment by ivan-ef** [comment]
> Hello,
> 
> You might have better luck using the very first release that supports Monterey and then trying to upgrade after the installation is fully completed.
> 
> I ran into the exact same issue when trying to use the latest installer with Big Sur (11.7), in the same spot.
> 
> What worked for me was to go back to 3.1.4 release, update the Big Sur installer, install Big Sur, install 3.1.4 to internal EFI and then after everything was verified working, switch to the latest 3.2.1 (which works fine after macOS is fully installed).

Looks like it was my mistake when messing with boot devices. I realized that there is a drug n drop scheme in bios boot devices list to change priority.

**Comment by ivan-ef** [comment]
The main issue that NUC stores bootloader in nvram and it should be reset to display correct boot devices.
For those who looking for solution you can try to boot from  efi shell built-in in bios. select correct fs*: and run opencore.efi
