### ISSUE TITLE
Can not access the config.plist when loading opencore

### ISSUE THREAD

**Issue by JasonLamv-t** [osy/HaC-Mini#1026]
**Describe the bug**
I installed win11 and Monterey on different disks and boot them via opencore. It works well in version 3.2.0.
But in v3.2.1, I do some boot config alteration to add the win11 boot item, which is the same in v3.2.0, and OC will be blocked and hint: OCST aborting corrupted config.plist file access
How can I fix it?

**Expected behavior**
Show the boot menu.

**Configuration**
- HaC Mini version [e.g: 2.0]: 3.2.1
- OSX version [e.g: 10.14.6]: Monterey | 12.4
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: INTEL SSDPEKKW512G8 , NVME
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: HP SSD EX900 250GB, NVME
- Display port(s) used [e.g: USB-C, mini DP]: HDMI
- Display resolution(s) [e.g: 4K, 5K]: 4K
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: BCM94360CS2

**Comment by CinFree** [comment]
https://github.com/osy/HaC-Mini/releases/tag/v3.1.5

Version 3.2.1 has boot security enabled by default,
If you do not enable boot security, then the installer did not install successfully,
You can choose "Customize" and check "Boot Options -> Disable boot security" in HaC Mini and in the installer
Try to fix this, or see the link above to enable boot security

**Comment by JasonLamv-t** [comment]
> https://github.com/osy/HaC-Mini/releases/tag/v3.1.5
> 
> Version 3.2.1 has boot security enabled by default, If you do not enable boot security, then the installer did not install successfully, You can choose "Customize" and check "Boot Options -> Disable boot security" in HaC Mini and in the installer Try to fix this, or see the link above to enable boot security

Appreciate your reply, it works!
