### ISSUE TITLE
crashed after upgrading to v3.2.1

### ISSUE THREAD

**Issue by simonmz20** [osy/HaC-Mini#1027]
**Describe the bug**
After I upgraded the hac-mini from v3.2.0 to v3.2.1 and reboot, but the system crashed after entering the password(sometimes before entering the password). It has been working well for a long time before this.
so I reinstall HaCMini.pkg v 3.2.0 on the USB on another macbook, reboot NUC from the USB，it worded.

**Comment by simonmz20** [comment]
so i want to find out the problem with it and upgrade the hac-mini, thanks for all

**Comment by osy** [comment]
Please note that secure boot is now installed by default. I forgot to mention this sorry will update the release notes.

**Comment by simonmz20** [comment]
Sorry to bother you again, but when I installed hac-mini v3.2.0, I checked Secure Boot and was able to boot and upgrade macos, but in hac-mini v3.2.1 it didn't boot properly, at which point I had followed the v3.1.5 release notes, and when I reinstalled v3.2.0, it booted properly again， thanks for your reply.

**Comment by simonmz20** [comment]
I hope to find out what's wrong with this. thanks for your reply again.
