### ISSUE TITLE
Hacmini Installation on clean 13.0 (Ventura) will display installation failure.

### ISSUE THREAD

**Issue by SpookHCK** [osy/HaC-Mini#1033]
**Describe the bug**
Clean install of Ventura, on a new SSD. 
ran xcode-select --install prior to running the install HaC Mini pkg

**Expected behavior**
installer fails with a generic "The installation failed."
![Screen Shot 2022-10-26 at 10 46 44 AM](https://user-images.githubusercontent.com/53403738/198086907-656f2caa-4fff-4dc2-9dfe-af4cb36e1ebf.png)

**Environment:**
 - Running OSX version: 
Clean install of 13.0
 - Target drive OSX version: 
Clean install of 13.0
 - HaC Mini installer version: 
[v3.2.1](https://github.com/osy/HaC-Mini/releases/tag/v3.2.1)

**Additional context**
The installer also fails to complete when Secure boot is disabled. "Boot Options -> Enable boot security". BIOS settings are same as in guide. Secure boot is disabled, usb charging off, thunderbolt legacy...
_EDIT_: BIOS version is BIOS Update [HNKBLi70] 9/22/2022

**Logs**
Please attach `/var/log/install.log`
[install.log](https://github.com/osy/HaC-Mini/files/9872066/install.log)

Thanks!

**Comment by SpookHCK** [comment]
Confirmed; I clean installed 12.6.1 and Secure boot option works as described. 
All options on 13.0 appear to result in failure. (I'll edit the first post to reflect this change.

**Comment by SpookHCK** [comment]
Clean installed 12.6.1 and Secure boot option works as described.
Upgraded to 13.0 via software update.
Same error HacMini.pkg fails on upgraded 13.0

Installer might need a rebuild for 13.0?

**Comment by hanziping** [comment]
Got same issue. Please help to take a look.
