### ISSUE TITLE
Error using HaC Mini installer on Catalina 10.15.7

### ISSUE THREAD

**Issue by fishnetstalker** [osy/HaC-Mini#1054]
I have a Hades Canyon NUC I'm wanting to convert to a HaC Mini. I have a MacBook Pro on Catalina 10.15.7 and was able to download the Catalina installer and put it on a USB stick. The HaC Mini installer fails when trying to install to the USB stick with or without the patch installer option. The guide indicates that I should be able to patch older MacOS, should I use older version of HaC Mini instead of latest or should I be using a newer OSX installer? It looks like a script is failing to move the EFI folder into the EFI partition?

Logs are attached.
[Installer Log 22-Dec-2022.txt](https://github.com/osy/HaC-Mini/files/10288479/Installer.Log.22-Dec-2022.txt)

Thanks for any help!

**Comment by osy** [comment]
It seems like the install didn’t actually fail. It just failed to unmount in the last step. Everything should still work.
