### ISSUE TITLE
Fresh install with hacmini 3.2.2 causes reboots and/or freezes

### ISSUE THREAD

**Issue by Littlehairs0925** [osy/HaC-Mini#1055]
**PLEASE READ THE FOLLOWING**
* Make sure you installed the latest version of HaC Mini
* Follow **all** the [troubleshooting steps](https://osy.gitbook.io/hac-mini-guide/post-installation/support)
* Check the open issues and make sure it is not already reported
* Delete this section from your report and continue

**Describe the bug**

**Expected behavior**

**Configuration**
- HaC Mini version [e.g: 2.0]: 
- OSX version [e.g: 10.14.6]: 
- NUC model [e.g: NUC8i7HNK]: 
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: 
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: 
- Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]: 
- Display resolution(s) [e.g: 4K, 5K]: 
- Any TB3 devices: 
- Any USB devices: 
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: 

**Modifications**
List any mods to `config.plist`, any additional kexts, anything installed to `/Library/Extensions` and `/System/Library/Extensions`, any additional patches, etc. Please attach your `config.plist` if you made any modifications.

**Panic log**
Include a screenshot of the panic message if applicable.
panic(cpu 4 caller 0xffffff801bbe54b4): [default.kalloc.16]: element modified after free (off:8, val:0x0000000000000002, sz:16, ptr:0xffffff90aee3c1f0)
    8: 0x0000000000000002
Panicked task 0xffffff90aea99208: 135 threads: pid 0: kernel_task
Backtrace (CPU 4), panicked thread: 0xffffff9a46c60598, Frame : Return Address
0xffffffcb2693f210 : 0xffffff801b3eb31d 
0xffffffcb2693f260 : 0xffffff801b559236 
0xffffffcb2693f2a0 : 0xffffff801b548480 
0xffffffcb2693f2f0 : 0xffffff801b385951 
0xffffffcb2693f310 : 0xffffff801b3eb5fd 
0xffffffcb2693f400 : 0xffffff801b3eaca9 
0xffffffcb2693f460 : 0xffffff801bbe08cb 
0xffffffcb2693f550 : 0xffffff801bbe54b4 
0xffffffcb2693f9c0 : 0xffffff801b45d991 
0xffffffcb2693fa20 : 0xffffff801b3fa5fb 
0xffffffcb2693fa40 : 0xffffff801bad11b0 
0xffffffcb2693fa60 : 0xffffff801d1c17ec 
0xffffffcb2693fab0 : 0xffffff801d1c19c3 
0xffffffcb2693fad0 : 0xffffff801d27031f 
0xffffffcb2693faf0 : 0xffffff801d2bb117 
0xffffffcb2693fb90 : 0xffffff801d1ce622 
0xffffffcb2693fc60 : 0xffffff801d1ccba6 
0xffffffcb2693fcd0 : 0xffffff801d1cc74f 
0xffffffcb2693fd00 : 0xffffff801bb15d54 
0xffffffcb2693fd60 : 0xffffff801d1cd88e 
0xffffffcb2693fdd0 : 0xffffff801bae8a62 
0xffffffcb2693fe30 : 0xffffff801bae85da 
0xffffffcb2693fef0 : 0xffffff801bae7640 
0xffffffcb2693ff50 : 0xffffff801baea747 
0xffffffcb2693ffa0 : 0xffffff801b38519e 
      Kernel Extensions in backtrace:
         com.apple.driver.AirPort.BrcmNIC(1400.1.1)[D35E9C22-17DD-30E6-BF29-1F3C10BCB958]@0xffffff801d1a2000->0xffffff801d6fafff
            dependency: com.apple.driver.corecapture(1.0.4)[3A3001CC-D289-35D6-B101-7B16A7F8AC9E]@0xffffff801e5f0000->0xffffff801e612fff
            dependency: com.apple.driver.mDNSOffloadUserClient(1.0.1b8)[A560C3FC-5D7E-3B9B-8B2D-425FB3ED908E]@0xffffff801ddf9000->0xffffff801ddfdfff
            dependency: com.apple.iokit.IO80211FamilyLegacy(1200.12.2b1)[63565270-42B3-31A8-80FB-16DA0EBBFA4C]@0xffffff801d040000->0xffffff801d186fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[196DFD8C-1D79-39E6-AEFA-FCF645C51977]@0xffffff801db9f000->0xffffff801dbb5fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[752CD69F-309E-31FF-881C-2A22ACB6C0B6]@0xffffff801de00000->0xffffff801de2ffff
            dependency: com.apple.iokit.IOSkywalkFamily(1.0)[F96DD1E4-1285-31A2-8AE8-4C6884D59E11]@0xffffff801dee9000->0xffffff801df16fff

Process name corresponding to current thread (0xffffff9a46c60598): kernel_task
Boot args: alcid=11 agdpmod=ignore -disablegfxfirmware shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2 igfxmetal=1

Mac OS version:
Not yet set

Kernel version:
Darwin Kernel Version 22.2.0: Fri Nov 11 02:08:47 PST 2022; root:xnu-8792.61.2~4/RELEASE_X86_64
Kernel UUID: 6B3374E9-7FD7-354D-886F-E995FAAC2CA3
roots installed: 0
KernelCache slide: 0x000000001b000000
KernelCache base:  0xffffff801b200000
Kernel slide:      0x000000001b0dc000
Kernel text base:  0xffffff801b2dc000
__HIB  text base: 0xffffff801b100000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file unavailable, panic occurred prior to initialization
Hibernation exit count: 0

System uptime in nanoseconds: 820111241
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x0000000030e1eaf3
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00001779af0cbaf7 0x0000000000000000
Compressor Info: 0% of compressed pages limit (OK) and 0% of segments limit (OK) with 0 swapfiles and OK swap space
Zone info:
  Zone map: 0xffffff80ac995000 - 0xffffffa0ac995000
  . PGZ   : 0xffffff80ac995000 - 0xffffff80b0996000
  . VM    : 0xffffff80b0996000 - 0xffffff857ccc9000
  . RO    : 0xffffff857ccc9000 - 0xffffff871632f000
  . GEN0  : 0xffffff871632f000 - 0xffffff8be2662000
  . GEN1  : 0xffffff8be2662000 - 0xffffff90ae995000
  . GEN2  : 0xffffff90ae995000 - 0xffffff957acc8000
  . GEN3  : 0xffffff957acc8000 - 0xffffff9a46ffb000
  . DATA  : 0xffffff9a46ffb000 - 0xffffffa0ac995000
  Metadata: 0xffffff8060985000 - 0xffffff8080985000
  Bitmaps : 0xffffff8080985000 - 0xffffff808c985000

**Comment by topiga** [comment]
Please make sure to fill in your configuration, the bug, the expected behaviour, and the modifications made.
