### ISSUE TITLE
SDXC stop working after update to macos Ventura 13.2

### ISSUE THREAD

**Issue by epicurei** [osy/HaC-Mini#1056]
**Bug**
The initial state was fully functional system with macOS 12.6.1 first installation with HACMINI 3.2.2. 
Automatically upgrading OC from 0.7.5 to 0.8.8, update of existing Kext and automatically updating of config.plist conformed to the new version of OC all operations performed by OCAT 20230006 for OC 0.8.8. 
I restarted everything and I verified the correct functioning of 12.6.1, after the updates made above, without encountering any problem. 
I then proceeded to install the update from 12.6.1 to 13.2, the installation took place without any problem but now the following entries have stopped working:

- SDXC slot
- WI-FI
- Bluetooth

**Expected behavior**
have all entries working as with version 12.6.1

**Starting Configuration**
- HaC Mini version 3.2.2: 
- OSX version 12.6.1: 
- NUC model NUC8i7HVK2: 
- Boot SSD model and protocol Samsung EVO Plus 970 1TB, NVME: 
- Second SSD model and protocol INTEL SSDSCKKW010X6, 1TB, SATA]: 
- First DIMM model Corsair DDR4-2666 32GB: 
- Second DIMM model Corsair DDR4-2666 32GB: 
- Display port(s) used rear HDMI: 
- Display resolution(s) 4K: 
- Any TB3 devices: none
- Any USB devices: mouse
- Any Wi-Fi/Bluetooth devices : Apple magic Keyboard 2 , magic mouse 2, magic trackpad 2

**Modifications**
none, update OC 0.7.5 -> 0.8.8, update existing Kext and config.plist automatically converted by OCAT v.20230006 for OpenCore 0.8.8

**Comment by topiga** [comment]
Which kexts are enabled ?

**Comment by epicurei** [comment]
with intel WIFI-BT card no operation both in monterey and in ventura, I then replaced the intel card with bcm94352z and the BT began to work with the monterey kexts configuration attached in monterey while in ventura no change with the same monterey kexts enabled and not even with the attached ventura kexts confguration

[monterey_ventura.zip](https://github.com/osy/HaC-Mini/files/10732967/monterey_ventura.zip)

**Comment by topiga** [comment]
Please link your EFI (zipped) without SMBIOS information

**Comment by topiga** [comment]
Try this
![image](https://user-images.githubusercontent.com/38886040/218782933-38a34110-a62a-46ef-ad9f-3d29f02459a3.png)
Also, I recommend you to use OCAT, not Opencore Configurator.

**Comment by epicurei** [comment]
Many thanks TOPIGA for your support, now both the WIFI and the BT work properly the only thing that still does not work is the sdxc reader in Ventura 13.2 while in Monterey 12.6.3 works correctly

**Comment by topiga** [comment]
I'm working on it, there will be pull requests to address multiple issues.

**Comment by epicurei** [comment]
yes, as in Ventura (see attachment) but in Monterey introducing an SD to the slot appears on the desktop the icon while in Ventura not
![IMG_E1289](https://user-images.githubusercontent.com/111680366/221198469-3203b6a1-5379-474c-876d-d59231f5b780.JPG)

**Comment by topiga** [comment]
Okay I found a fix. I’ll give you the fix soon.

**Comment by topiga** [comment]
Okay so please add this kext : [CtlnaSDXC.kext.zip](https://github.com/osy/HaC-Mini/files/10834601/CtlnaSDXC.kext.zip)
It's the kext used in OCLP to add support to SDXC readers on unsupported Macs. Let me know !

**Comment by ivan-ef** [comment]
> It's the kext used in OCLP to add support to SDXC readers on unsupported Macs. Let me know !


Should I replace old sdxc kext with it or just add new?

**Comment by ivan-ef** [comment]
> It's the kext used in OCLP to add support to SDXC readers on unsupported Macs. Let me know !

If I just add new kext system doesn't start [image](https://user-images.githubusercontent.com/67600440/221494021-51dac4ae-8d3a-49b5-9606-ce514b088be8.jpeg)

**Comment by topiga** [comment]
Yes sorry, you need to set Max Kernel for the old one to 20.99.99 and Min Kernel for the new one to 21.0.0
I should’ve mentioned that.

**Comment by topiga** [comment]
Yes sorry, you need to set Max Kernel for the old one to 20.99.99 and Min Kernel for the new one to 21.0.0
I should’ve mentioned that.

**Comment by epicurei** [comment]
Many thanks TOPIGA for your support, now SDXC card reader work properly also in Ventura 13.2.1

**Comment by topiga** [comment]
Great ! Don’t close this feed until a release is made to cover these issues.

**Comment by topiga** [comment]
Hey again, can you test this kext [this kext](https://github.com/osy/HaC-Mini/files/10850326/BigSurSDXC.kext.zip) and tell me if it's working as well ?

**Comment by ivan-ef** [comment]
> Hey again, can you test this kext [this kext](https://github.com/osy/HaC-Mini/files/10850326/BigSurSDXC.kext.zip) and tell me if it's working as well ?
> 
> As always, disable the other kexts for SDXC before.
> 
> 

I Will also test it today or tomorrow. As ctlnaSDXC didn't work for me as well.

**Comment by topiga** [comment]
> I Will also test it today or tomorrow. As ctlnaSDXC didn't work for me as well.
Nothing was working with NUCO2SDXC disabled and CtlnaSDXC enabled ?

**Comment by ivan-ef** [comment]
> > I Will also test it today or tomorrow. As ctlnaSDXC didn't work for me as well.
> 
> 
> 
> Nothing was working with NUCO2SDXC disabled and CtlnaSDXC enabled ?

Yes.  I tried to disable NUCO and enable Ctlna. Card reader not appear in system info nor sd card appear when plugged.

**Comment by topiga** [comment]
What version of the pkg are you using and what is the version of macOS installed ?

**Comment by ivan-ef** [comment]
> What version of the pkg are you using and what is the version of macOS installed ?

MacOS 12.6

Hac mini 3.2.2

**Comment by topiga** [comment]
You can’t read SD cards on Monterey ?

**Comment by ivan-ef** [comment]
> You can’t read SD cards on Monterey ?

With NUCO kext I can read cards on Monterey. 
But card reader does not appear in system system report. Speed very slow <8mb/s and cards formatted to fat32 doesn't appear at all.
(very strange behavior :-))

**Comment by ivan-ef** [comment]
> Hey again, can you test this kext [this kext](https://github.com/osy/HaC-Mini/files/10850326/BigSurSDXC.kext.zip) and tell me if it's working as well ?
> As always, disable the other kexts for SDXC before.

I tested new kext and it works. still does not appear in system system reports, but now speeds are 20Mb/s / 20Mb/s. Much better than before but still not as fast as my cheap generic USB3.0 card reader - 28Mb/s / 80Mb/s.

THANKS FOR MAKING OUR NUCs BETTER!

**Comment by ivan-ef** [comment]
> You can’t read SD cards on Monterey ?

I can't get card reader to work again. 
Could you send me your OC folder so I can compare with mine and understand what do I making wrong?

**Comment by SashonIT** [comment]
@topiga  WOW...  

Great Work and great Solution.... like a Fingersnip and the SD Card Reader is Working.

So many Thanks to you.

**Comment by osy** [comment]
@topiga can you detail what you did so we can add this to the next update?

**Comment by topiga** [comment]
I added [BigSurSDXC](https://github.com/osy/HaC-Mini/files/10850326/BigSurSDXC.kext.zip) in config.plist, with min-kernel to 21.0.0 and no max-kernel. I added a max-kernel of 20.99.99 to NUCO2SDXC.kext.
I would love to make a commit request, but I don’t know much about packages…
This kext is from OpenCore Legacy Patcher.

**Comment by ivan-ef** [comment]
> I added [BigSurSDXC](https://github.com/osy/HaC-Mini/files/10850326/BigSurSDXC.kext.zip) in config.plist, with min-kernel to 21.0.0 and no max-kernel. I added a max-kernel of 20.99.99 to NUCO2SDXC.kext.

It's working again, thanks!! You should add this to your pull request.

**Comment by xjwan110** [comment]
I added [BigSurSDXC](https://github.com/osy/HaC-Mini/files/10850326/BigSurSDXC.kext.zip) in config.plist,but it is not work.As ctlnaSDXC didn't work for me as well.
OS X version is 13.2.1.

**Comment by xjwan110** [comment]
> **Bug** The initial state was fully functional system with macOS 12.6.1 first installation with HACMINI 3.2.2. Automatically upgrading OC from 0.7.5 to 0.8.8, update of existing Kext and automatically updating of config.plist conformed to the new version of OC all operations performed by OCAT 20230006 for OC 0.8.8. I restarted everything and I verified the correct functioning of 12.6.1, after the updates made above, without encountering any problem. I then proceeded to install the update from 12.6.1 to 13.2, the installation took place without any problem but now the following entries have stopped working:
> 
> * SDXC slot
> * WI-FI
> * Bluetooth
> 
> **Expected behavior** have all entries working as with version 12.6.1
> 
> **Starting Configuration**
> 
> * HaC Mini version 3.2.2:
> * OSX version 12.6.1:
> * NUC model NUC8i7HVK2:
> * Boot SSD model and protocol Samsung EVO Plus 970 1TB, NVME:
> * Second SSD model and protocol INTEL SSDSCKKW010X6, 1TB, SATA]:
> * First DIMM model Corsair DDR4-2666 32GB:
> * Second DIMM model Corsair DDR4-2666 32GB:
> * Display port(s) used rear HDMI:
> * Display resolution(s) 4K:
> * Any TB3 devices: none
> * Any USB devices: mouse
> * Any Wi-Fi/Bluetooth devices : Apple magic Keyboard 2 , magic mouse 2, magic trackpad 2
> 
> **Modifications** none, update OC 0.7.5 -> 0.8.8, update existing Kext and config.plist automatically converted by OCAT v.20230006 for OpenCore 0.8.8

hello, could you send your EFI for me? which EFI is work fine.Thanks!

**Comment by ivan-ef** [comment]
> I added [BigSurSDXC](https://github.com/osy/HaC-Mini/files/10850326/BigSurSDXC.kext.zip

You should also set
min-kernel to 21.0.0 of BigSurSDXC AND max-kernel of 20.99.99 to NUCO2SDXC.kext.

**Comment by xjwan110** [comment]
> 

yes，I have done it，but it does not work.. could you send your EFI for me?

**Comment by mheyl** [comment]
Is it possible to add this SDXC fix into the next - or possible interim release of Hac-Mini? I noticed - besides OC 9 - there are also quite some new releases for various .kexts now. Point is - I am not very familiar dealing with the plist file and adding / changing kexts manually... - and a Hac-Mini Maintenance Release would be necessary (now with the Graphics issues with Ventura 13.3 even more so I guess)..

**Comment by ivan-ef** [comment]
> Is it possible to add this SDXC fix into the next - or possible interim release of Hac-Mini?

If u want to install hackintosh the only way to make it is to study some basic stuff.

**Comment by osy** [comment]
I’m traveling currently, will plan to do an update when I get back but as it says in the release notes, this project is winding down. Soon, no more updates will be provided so keep that in mind.

**Comment by ivan-ef** [comment]
hopefully some contributors who are also interested in this project wil continue to improve it.

**Comment by SashonIT** [comment]
> Is it possible to add this SDXC fix into the next - or possible interim release of Hac-Mini? I noticed - besides OC 9 - there are also quite some new releases for various .kexts now. Point is - I am not very familiar dealing with the plist file and adding / changing kexts manually... - and a Hac-Mini Maintenance Release would be necessary (now with the Graphics issues with Ventura 13.3 even more so I guess)..

i can provide my OpenCore 0.9.0 DEBUG EFI tomorrow. which is running perfectly with everything in 13.2.1

everything is working like on a real mac. 

also thunderbolt 3 with antelope audio interface.

but you need to install OCAT.

**Comment by SashonIT** [comment]
> I’m traveling currently, will plan to do an update when I get back but as it says in the release notes, this project is winding down. Soon, no more updates will be provided so keep that in mind.
First of all…. have super Fun at your travels …. :-)
it definitely needs a new Graphics Fix.

same problem that was under mojave and later in a Version of Big Sur.

**Comment by mheyl** [comment]
> i can provide my OpenCore 0.9.0 DEBUG EFI tomorrow. which is running perfectly with everything in 13.2.1
> 
> everything is working like on a real mac.
That could be a starting point.. - so far, basically all HacMini releases made me feel like I am on a real Mac...; which is why I was "careless" and went to 13.3 (instead of 13.2.1)... with the now prominent graphics issues.. (more an annoyance then a real show stopper..). If I could make the reader work again would be cool already.. - so post you EFI and I ma find a way...

**Comment by xjwan110** [comment]
> > 是否可以将此SDXC修复程序添加到Hac-Mini的下一个或可能的临时版本中？我注意到-除了OC 9-现在还有相当多的各种.kexts的新版本。重点是-我不太熟悉处理plist文件和手动添加/更改kexts...-需要Hac-Mini维护版本（现在Ventura 13.3的图形问题更是如此，我猜）。
> 
> 我明天可以提供我的OpenCore 0.9.0 DEBUG EFI。它与13.2.1中所有内容完美运行
> 
> 一切都像在真正的Mac上一样工作。
> 
> 还有带有羚羊音频接口的雷雳3。
> 
> 但你需要安装OCAT。

Can you show me your EFI?

**Comment by xjwan110** [comment]
> > Is it possible to add this SDXC fix into the next - or possible interim release of Hac-Mini? I noticed - besides OC 9 - there are also quite some new releases for various .kexts now. Point is - I am not very familiar dealing with the plist file and adding / changing kexts manually... - and a Hac-Mini Maintenance Release would be necessary (now with the Graphics issues with Ventura 13.3 even more so I guess)..
> 
> i can provide my OpenCore 0.9.0 DEBUG EFI tomorrow. which is running perfectly with everything in 13.2.1
> 
> everything is working like on a real mac.
> 
> also thunderbolt 3 with antelope audio interface.
> 
> but you need to install Can you show me your EFI?

**Comment by xjwan110** [comment]
> > Is it possible to add this SDXC fix into the next - or possible interim release of Hac-Mini? I noticed - besides OC 9 - there are also quite some new releases for various .kexts now. Point is - I am not very familiar dealing with the plist file and adding / changing kexts manually... - and a Hac-Mini Maintenance Release would be necessary (now with the Graphics issues with Ventura 13.3 even more so I guess)..
> 
> i can provide my OpenCore 0.9.0 DEBUG EFI tomorrow. which is running perfectly with everything in 13.2.1
> 
> everything is working like on a real mac.
> 
> also thunderbolt 3 with antelope audio interface.
> 
> but you need to install OCAT.

Can you show me your EFI?

**Comment by maxpicelli** [comment]
Hi all, im notice that CtlnaSDXC.kext works very fine on Sonoma WITHOUT OCLP. 
Just need config your DeviceProperties with your pcidevice extracted from Hackintool and put some args and change the plist inside kext to the same device that yours. 

For exemple that mine is pci1217,8621 

![Captura de Tela 2023-12-16 às 20 04 07](https://github.com/osy/HaC-Mini/assets/115906479/2c83b287-b0a2-45ea-bfe0-cbe4848f97bc)

![Captura de Tela 2023-12-16 às 20 02 45](https://github.com/osy/HaC-Mini/assets/115906479/31573045-f7c2-4438-843a-6fa30a0dbbb1)

![WhatsApp Image 2023-12-16 at 19 55 41](https://github.com/osy/HaC-Mini/assets/115906479/b7294855-c2d2-43c0-bc16-9dc0fd70da2c)

[CtlnaSDXC.kext + SD CARD DEVICE PROPERTIES LENOVO SONOMA.zip](https://github.com/osy/HaC-Mini/files/13694181/CtlnaSDXC.kext.%2B.SD.CARD.DEVICE.PROPERTIES.LENOVO.SONOMA.zip)

**O2 Micro** SD CARD 

> Okay so please add this kext : [CtlnaSDXC.kext.zip](https://github.com/osy/HaC-Mini/files/10834601/CtlnaSDXC.kext.zip). You also **_need_** to set **Max Kernel** for the old one to **20.99.99** and **Min Kernel** for the new one to **21.0.0**
> 
> It's the kext used in OCLP to add support to SDXC readers on unsupported Macs. Let me know !

**Comment by SashonIT** [comment]
@maxpicelli   ---> I did exactly what you wrote down.

Its not working?  What do i wrong?  Can you help me?

I am on Sonoma 14.2 and love to have the SD Card Reader running in Sonoma if possible.

Shall i upload my EFI or config.plist?

**Comment by maxpicelli** [comment]
Hi my SD Card work fine now. 
1. Need check the spec from your device. 
2. Need use Hackintool and extract your device properties (could be different about mine). 
3. Need wrote compatible and add in your config plist
4. Need install Kext
5. Need check OC Clean Snapshot with ProperTree to insert parameters on your config plist or use Opencore Configurator.
6. Need change your kext plist in show content package and just put the same parameters on you config.plist from kext downloaded. 
7. Restart and need work with any System. Need check if your USB Map was made correctly.

**Comment by maxpicelli** [comment]
Maybe you need check if you got copy steps to make work. Are you know how to check YOUR Device Properties ? 
If you SD Card reader was not compatible, not will work. If you made exactly and not work, maybe you need try RestNvram and Never use OCAT, because this program crack your config.plist. I saw your EFI on your page, an seems to me that you use OCAT, and this garbage program crack all EFIs.

**Comment by SashonIT** [comment]
Yes i use OCAT ---> HAHA.  Nice to hear, that this Programm is not the best.

I also have Hackintool Installed.
<img width="1708" alt="image" src="https://github.com/osy/HaC-Mini/assets/126977959/1a7c968f-9600-4a76-bfc3-fab9270a2335">

PciRoot(0x0)/Pci(0x1,0x2)/Pci(0x0,0x0).  The Difference ist in the Device Path.

The Rest is the same --> IOService:/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/PEG2@1,2/IOPP/PEGP@0

1217,8621

I can use Xplist to make the entries.
I set the minKernel for CtlnaSDXC.kext to 21.0.0 ---> is this correct?
@maxpicelli 
Can you watch my Config.plist?

[SdCardConfig.plist.zip](https://github.com/osy/HaC-Mini/files/13694489/SdCardConfig.plist.zip)

**Comment by maxpicelli** [comment]
Yes but I need your device plist extracted from Hakcitool

**Comment by maxpicelli** [comment]
This part is the same of mine?

Internal@0,28,4/0,0 ?

**Comment by maxpicelli** [comment]
You boot args is to much arguments. I not sure if you need use all of that
Many devices on you machine
How specs are you using? Laptop ? Desktop?

**Comment by maxpicelli** [comment]
If you are using OCAT and OCLP so sorry but this maybe cause conflicts with your hardware 

Try contact to me on my discord group. My Nick Name Max.1974

https://discord.gg/quQDHChTBj

**Comment by SashonIT** [comment]
Bootargs are Fine. I use the NUC 8I7HVK which was this repository was build for.  Everything running fine on my MAschine except of the SDCard Reader Build in.  It was running in Ventura. but not with FullSpeed.

And now you came along with this news.

Here is the exported DeviceList from Hackintool. --->
[HackintoolPCIDeviceList.zip](https://github.com/osy/HaC-Mini/files/13694527/HackintoolPCIDeviceList.zip)


Yes i am using OCLP 1.3.0 . Because of WIFI.

**Comment by maxpicelli** [comment]
Your SMBIOS its something wrong, Macmini8,1 without serial? Or you take off? If you was using Laptop more useful MacbooPro15,2

**Comment by SashonIT** [comment]
I took the SERIAL out.
And SMBIOS HAs to be Macmini 8,1 nothing else.

Like i said. Everything is fine and Stable. Except of the SDCard Reader.

I dont wanna Destroy my MAschine.  Its a Music Making MAschine. Do wanna Install again.  Kepp this in Mind.

**Comment by maxpicelli** [comment]
![Captura de Tela 2023-12-16 às 23 55 55](https://github.com/osy/HaC-Mini/assets/115906479/2c9a070f-991a-4883-bf3c-b57fa75b6b97)

Your address you copy from mine (like im imagine) so you need use yours.

**Comment by maxpicelli** [comment]
[SDCard-Device.plist.zip](https://github.com/osy/HaC-Mini/files/13694536/SDCard-Device.plist.zip)

Copy and replace from DeviceProperties and save config.plist. Put Kext on kext folder and Need Run Propertree and click on OC Clean Snapshot Menu. (can you do it?)

**Comment by SashonIT** [comment]
Its Running, due to Help of @maxpicelli 

Thank you Man.
But only recognizing up to 32 GB Cards. There is the END. 64 GB and 128GB not recognizing

**Comment by maxpicelli** [comment]
Enjoy it my friend!! Thanks!!
