### ISSUE TITLE
DSXC not working properly OS 12.6

### ISSUE THREAD

**Issue by ivan-ef** [osy/HaC-Mini#1057]
DSXC card reader doesn't appear in system report. It reads SD cards, but speed is only 4MB/s on all cards. cards formatted to FAT32 does not appear after insertion. FAT16 and HFS does.

NUCO2SDXC.kext is present and enabled in config.plist

**Configuration**
- HaC Mini version 3.2.2
- OSX version 12.6
- NUC model NUC8i7HVK

**Comment by topiga** [comment]
4MB/s for an SDHC card seems normal, otherwise, see #1056

**Comment by ivan-ef** [comment]
#1056
