### ISSUE TITLE
【OS Version 13.3.1】bluetooth do not work after wake up

### ISSUE THREAD

**Issue by sxz799** [osy/HaC-Mini#1062]
macos : 13.3.1
ngff card :bcm94360cs2
ssd : sn550
bluetooth device : logitech k380
bios Version : 0070
HacMini 3.3.1

I found that the K380 keyboard can wake up Hades, but after waking up, the Bluetooth cannot connect. I have to turn on Bluetooth again in the system settings to make it work.

I have a PC, and I also encountered the same problem, but if I turn off XMP in the BIOS, the problem can be solved.

I couldn't find the option to turn off XMP in the Hades BIOS. So, I tried to manually set the memory timing, which made the NUC not work.

Then I removed the yellow jumper on the motherboard, pressed the F2 key to enter the BIOS, and changed the memory timing to normal values in the BIOS.

When I entered the system, the problem was solved. If I turn off the power and plug in the power again, when I press the power button, the LED will turn to the default color, and after about 2 seconds, the LED will turn red (manually set in the BIOS).

Therefore, I guess the problem is related to the memory XMP configuration.

[![ppQMl5V.png](https://s1.ax1x.com/2023/03/13/ppQMl5V.png)](https://imgse.com/i/ppQMl5V)

**Comment by topiga** [comment]
I have the same card, the same version of macOS, and it works. That's weird.

**Comment by sxz799** [comment]
> I have the same card, the same version of macOS, and it works. That's weird.

May I know the type and frequency of the RAM you are using?

**Comment by topiga** [comment]
2x16GB 2400Mhz

**Comment by sxz799** [comment]
> 2x16GB 2400Mhz

 bios version ?

**Comment by sxz799** [comment]
> Before any of this, update to HaC Mini 3.3.1, then come back

update to HaC Mini 3.3.1 and macos 13.3.1，the problem still exists.

**Comment by sxz799** [comment]
update 13.4 , the problem disappeared

**Comment by sxz799** [comment]
update 13.4 , the problem disappeared
