### ISSUE TITLE
macOS 12.6.4 Airplay and sidecar not showing up

### ISSUE THREAD

**Issue by lesser-panda** [osy/HaC-Mini#1074]
**Describe the bug**
I tried to enable sidecar to my iPad Pro but cannot find anything related to screen mirroring or Airplay on macOS 12.6.4. 
I have enabled iGPU in bios and chose the default Intel Decoder while installing the Hac Mini pkg.

Great project btw, thanks for all the hard work!

<img width="668" alt="image" src="https://user-images.githubusercontent.com/40119257/229359339-fed9447b-4a22-4ee0-8e79-73c619388155.png">
<img width="322" alt="image" src="https://user-images.githubusercontent.com/40119257/229359361-53e56856-a245-4817-8287-16f415e5ed98.png">

**Expected behavior**
Options for Airplay should show up in System Preferences and Control Center

**Configuration**
- HaC Mini version: 3.2.2
- OSX version: 12.6.4 
- NUC model: NUC8i7HVK
- Boot SSD model and protocol: Samsung 970 EVO 256G, NVME
- Second SSD model and protocol: WD Blue WDC WDS500G SATA
- Display port(s) used: USB-C
- Display resolution(s): 4K
- Any Wi-Fi/Bluetooth devices: BCM94360NG

**Modifications**
None

**Comment by osy** [comment]
Did you follow https://support.apple.com/en-us/HT210380

**Comment by lesser-panda** [comment]
@osy 
> Did you follow https://support.apple.com/en-us/HT210380

Yes according to the page, on Monterey, I should find the settings in 

> macOS Monterey: Choose Apple menu  > System Preferences, then click Displays. Click Display Settings, then click your iPad in the sidebar.

Unfortunately just like in the screenshot I provided, the settings are not there. I have connected my iPad and my NUC to the same WiFi.

**Comment by osy** [comment]
Are they logged in to the same Apple ID?

**Comment by lesser-panda** [comment]
> Are they logged in to the same Apple ID?

Yes they are using the same Apple ID

**Comment by lesser-panda** [comment]
@osy 
After a few restarts the problem was resolved. The airplay setting magically appeared in the System Preferences. Closing this ticket. Thanks again for the great work！
