### ISSUE TITLE
Cannot update Catalina using v3.3.1 installer.

### ISSUE THREAD

**Issue by Malumen** [osy/HaC-Mini#1086]
**Describe the bug**
Running the v3.3.1 installer, I get an error that it failed. Literally the _"The Installer encountered an error that caused the installation to fail"_ error. This is the first time I have ever encountered this error.

**Expected behavior**
Running the installer upgrades me to the latest HaC mini project.

**Environment:**
 - Running OSX version: 10.15.7
 - Target drive OSX version: 10.15.7
 - HaC Mini installer version: v3.3.1

**Additional context**
After the installer fails, I check the `EFI` folder to see that the `BOOT` and `Microsoft` folders are present, but the `OC` folder was deleted.

**Logs**
Please attach `/var/log/install.log`
Where can I find this? --> nvm found it. For everyone else: when running installer, don't close the window; when it fails, go. to the taskbar and then logs and then save the logs.
[Installer Log 29-Apr-2023.txt](https://github.com/osy/HaC-Mini/files/11358571/Installer.Log.29-Apr-2023.txt)

NOTE:
I intend to update to Big Sur in May but will likely hold off on Monterey and Ventura due to the secure-boot requirement (bricking people's NUCs).

**Comment by osy** [comment]
I see

```
Apr 29 15:48:02 USERNAME-mini package_script_service[1203]: ./postinstall: umount: /Volumes/MACOS1TB/private/tmp/EFIROOTDIR: not currently mounted
Apr 29 15:48:02 USERNAME-mini package_script_service[1203]: ./postinstall: rm: /Volumes/MACOS1TB/private/tmp/EFIROOTDIR: is a directory
```

It’s the last step which unmounts EFI. You should have upgraded successfully even though it reported error.

**Comment by Malumen** [comment]
> I see
> 
> ```
> Apr 29 15:48:02 USERNAME-mini package_script_service[1203]: ./postinstall: umount: /Volumes/MACOS1TB/private/tmp/EFIROOTDIR: not currently mounted
> Apr 29 15:48:02 USERNAME-mini package_script_service[1203]: ./postinstall: rm: /Volumes/MACOS1TB/private/tmp/EFIROOTDIR: is a directory
> ```
> 
> It’s the last step which unmounts EFI. You should have upgraded successfully even though it reported error.

Unfortunately, none of the kexts are updated, nothing has been affected.

**Comment by Malumen** [comment]
Here is the latest version of the `log`
[Installer Log 29-Apr-2023c.txt](https://github.com/osy/HaC-Mini/files/11358959/Installer.Log.29-Apr-2023c.txt)

Also, I am wrong: I am currently using `v3.1.3`. @osy should I make a new issue? Any way to re-open this ticket?

**Comment by Malumen** [comment]
Okay, running ANY `HaC mini` installer fails. Also, pointing the installer to my USB drive for Catalina Installer and checking the "patch Catalina USB Installer" also fails. Also aiming it at my external HDD with my clone also fails.

Again, running the installer _deletes the OC folder_ from the EFI partition. Nothing is installed.

I booted into recovery and ran `csrutil disable` to disable SIP, and still nothing succeeds.

Do I need to open a new issue?

**Comment by osy** [comment]
Can you try https://github.com/osy/HaC-Mini/suites/12567655805/artifacts/671886704

**Comment by Medizinmann-MD** [comment]
I have the same problem. 

Is there a version of the Installer that incorporates this fix?

Thanks and best regards.
