### ISSUE TITLE
Couldn't personalize volume /Volumes/Macintosh HD

### ISSUE THREAD

**Issue by mokapsing** [osy/HaC-Mini#340]
**PLEASE READ THE FOLLOWING**
* Make sure you installed the latest version of HaC Mini
* Follow **all** the [troubleshooting steps](https://osy.gitbook.io/hac-mini-guide/post-installation/support)
* Check the open issues and make sure it is not already reported
* Delete this section from your report and continue

**Describe the bug**

I updated the have mini to 2.13, checked oc secure boot, then it automatically rebooted to recovery mode, then I ran bless --folder "/Volumes/Macintosh HD/System/Library/CoreServices" --bootefi --personalize in the terminal, but it said "Couldn't personalize volume /Volumes/Macintosh HD"
![D3FA29BD-902F-41B4-8B4F-876FD9C4C996](https://user-images.githubusercontent.com/39441028/95337461-6f6e5700-08e4-11eb-9f46-fec2f0a07a55.jpeg)

**Expected behavior**
I think it should be successfully done
**Configuration**
- HaC Mini version [e.g: 2.0]: 2.13
- OSX version [e.g: 10.14.6]: latest stable
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Intel 760p 512GB
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: Intel 760p 512GB
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: 
- Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]: 
- Display resolution(s) [e.g: 4K, 5K]: 
- Any TB3 devices: 
- Any USB devices: 
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: 

**Modifications**
List any mods to `config.plist`, any additional kexts, anything installed to `/Library/Extensions` and `/System/Library/Extensions`, any additional patches, etc. Please attach your `config.plist` if you made any modifications.

**Panic log**
Include a screenshot of the panic message if applicable.

**Comment by osy86** [comment]
Is the name of your partition “Macintosh HD”? What version of macOS is installed?

**Comment by mokapsing** [comment]
now how could I show you this msg?

**Comment by osy86** [comment]
`ls /Volumes` should show you all your OS X installs.

**Comment by mokapsing** [comment]
The partition name should be ok, and the version is 10.15.6
![8E9913F0-4E51-431B-9063-415C51482D13](https://user-images.githubusercontent.com/39441028/95399144-13362200-093a-11eb-9fd5-b8160014af40.jpeg)
BTW , I could enter winOS

**Comment by mokapsing** [comment]
Any way to save my Marcos?
![image](https://user-images.githubusercontent.com/39441028/95399821-a6238c00-093b-11eb-86cd-e86c204a92d2.jpg)

**Comment by mokapsing** [comment]
@osy86 any way to disable the SecureBoot by edit the plist in efi or other files?

**Comment by osy86** [comment]
Can you post your config.plist? I’m trying to figure out why some people have this problem and others don’t.

**Comment by mokapsing** [comment]
@osy86 I packed all of the OC folder in efi
[OC.zip](https://github.com/osy86/HaC-Mini/files/5345451/OC.zip)

**Comment by osy86** [comment]
Can you run First Aid from Disk Utility?

**Comment by osy86** [comment]
Oh and also make sure you have network available and can ping apple.

**Comment by mokapsing** [comment]
@osy86 I ran First Aid, still failed to boot, do you mean that I can re-install macOS online just like a macbook?

**Comment by mokapsing** [comment]
@osy86 Finally I saved my macOS, what I did: 1. do First Aid; 2. disabled my 2nd ssd; 3. run ```bless --folder "/Volumes/Macintosh HD/System/Library/CoreServices" --bootefi --personalize``` and succeeded. I remember that long time ago when I installed macOS, dual ssd made me hard to install it, I succeeded after I disabled one of them

**Comment by osy86** [comment]
I see, I will mention this in the guides.

**Comment by mokapsing** [comment]
diskutil and bootcamp also hard to process dual ssd

**Comment by goodbest** [comment]
I had the same issue with bless-personalize.
The recovery bash says `Can't determine mount point of '/Volumes/xxxx/System/Library/CoreServices' and ''`.

The straightforward solution is to disable the second ssd in bios, and then run the command again.
No need to run first aid beforehand.

**Comment by IIWare** [comment]
@osy86 very off-topic but I would like to know, did you accidentally block me in utmapp/UTM? I don't know how else I can let you know, so I decided to ask you, so did you actually block me or did you block me in utmapp/UTM by accident? I know, this comment could be frustrating but once again I would like you to know, if you answer me I will delete this comment, thanks.

**Comment by osy86** [comment]
@IIWare you ignored https://github.com/utmapp/UTM/issues/679#issuecomment-732660592 and immediately proceeded to at me in a spam thread and made it harder to take care of.

**Comment by IIWare** [comment]
to osy86: I am very sorry, I deleted all my comments in spams, but what I don't understand about your comment is "Especially don’t mention people or you might get banned accidentally in the crossfire." but you never said "or you might accidentally get banned in utmapp/UTM" but sorry, I will not reply to spam threads ever again, hopefully you can unblock me from utmapp/UTM, thanks.

**Comment by osy86** [comment]
@IIWare I will unban you but this is your last warning. Do you reply in spam threads, do not mention people in spam threads, do not make new threads about the spam. It is worse than the spam itself because that can be deleted automatically but I have to manually deal with your off-topic replies.

**Comment by IIWare** [comment]
osy86 thanks for unbanning me, and I will not reply in spams, not mention people in spams. and not make new threads about spam.

**Comment by IIWare** [comment]
> @IIWare I will unban you but this is your last warning. Do not reply in spam threads, do not mention people in spam threads, do not make new threads about the spam. It is worse than the spam itself because that can be deleted automatically but I have to manually deal with your off-topic replies.

Osy, sorry you took my issue that way, the issue was just an idea to let people know what to do when there are spam issues, so that they wouldn't get banned by accident, once again sorry.

**Comment by osy** [comment]
I was very clear

> do not make new threads about the spam

Your ban is for 30 days but if this happens again it’ll be permanent.

**Comment by osy** [comment]
Added troubleshooting to guide: https://osy.gitbook.io/hac-mini-guide/post-installation/support
