### ISSUE TITLE
Installer won't patch macOS Big Sur Beta 7 and results in error

### ISSUE THREAD

**Issue by mr-vito** [osy/HaC-Mini#342]
**Describe the bug**
I have created a new clean USB installer stick with macOS Big Sur Beta 7, and applied my HacMini 2.13 on it via the already installer macOS Big Sur Beta 2 version. HacMini Installer shows USB stick is not an Installer, although it is.

So, I just copied EFI folder from SSD EFI to USB EFI folder.

Whenever I boot, it gets stuck at pci config.

Dortania mentions an issue with Intel HEDT motherboards.

See: https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur/#stuck-at-pci-configuration-begins-for-intel-s-hedt-boards

**Expected behavior**
HacMini 2.13 should allow me to select my USB Installer automatically to patch and should also allow me to boot into the Installer as this is now supported with the new version of OpenCore for a clean install?

Also, checked source code of patch_installer.sh in HacMini and Big Sur InstallInfo.plist is missing?

**Environment:**
 - Running OSX version: macOS 11.0 Beta 2
 - Target drive OSX version:  macOS 11.0 Beta 7
 - HaC Mini installer version: 2.13

**Additional context**
Using Crucial MX500 SATA SSD as target disk

**Logs**
Cannot boot, hence no log

**Comment by goodbest** [comment]
If you have already applied 2.13 to your USB, then you don't have to copy SSD EFI into your USB EFI (as this operation will overwrite your 2.13 EFI in your USB.

BTW, you can just ignore `the installer patch` option. You can just re-run the 2.13 installer manually after you set up your system.

**Comment by mr-vito** [comment]
> If you have already applied 2.13 to your USB, then you don't have to copy SSD EFI into your USB EFI (as this operation will overwrite your 2.13 EFI in your USB.
> 
> BTW, you can just ignore `the installer patch` option. You can just re-run the 2.13 installer manually after you set up your system.

Thanks @goodbest !

So the problem is that I had to copy the EFI folder from my actual SSD rather than patching it from HacMini. Mine was just a workaround basically...

However, the Intel HEDT issue remains and I cannot boot into the Installer...

**Comment by osy86** [comment]
I’m confused at what you did. Copy the EFI? That’s not part of the guide. Can you follow the guide again from the start? Including checking your BIOS settings.

**Comment by keatliang2005** [comment]
today i try to create a usb installer stick with macOS 11.0.1, 
the hack mini installer v2.14, patch osx installer option is grey out, i proceed without that option anyway

then i try to boot from usb for macOS 11.0.1 installer, then i encounter this

![image](https://user-images.githubusercontent.com/473990/99146475-7b9fbe00-26b3-11eb-8e93-30a39d5edb8c.png)

it seems like it stuck on the boot loop

here's my option

![Screenshot 2020-11-14 at 7 57 56 PM](https://user-images.githubusercontent.com/473990/99146507-c8839480-26b3-11eb-87eb-5ff9b31c2724.png)
![Screenshot 2020-11-14 at 7 58 10 PM](https://user-images.githubusercontent.com/473990/99146508-cb7e8500-26b3-11eb-8691-517c9e9bdf74.png)
![Screenshot 2020-11-14 at 7 58 20 PM](https://user-images.githubusercontent.com/473990/99146509-ce797580-26b3-11eb-967c-b9be847218d7.png)

**Comment by fahdriyami** [comment]
I was attempting a clean install today of Big Sur 11.0.1 using v2.14. Also saw that the Patch OS X option is disabled. I will hold off on continuing this guide until a version is released that supports Big Sur.

**Comment by osy** [comment]
Closing since the original issue seems to be resolved.
