### ISSUE TITLE
Only 3840x2160 source output in windows with 5K display

### ISSUE THREAD

**Issue by qibinghua** [osy/HaC-Mini#352]
But my screen monitor is 5120x2160.

Is any idea for fix that?

**Comment by osy86** [comment]
No issue when booting directly without OC?

**Comment by cuteluo1983** [comment]
After using a uncertain version of hac-mini，whether it's the Big Sur or Catalina, my 4K monitor resolution is recognized incorrectly, causing it to shrink and then zoom in when booting into the desktop, and occasionally flashing, with the previous hac-mini version, there is no such problem, thanks!
![untitled 1](https://user-images.githubusercontent.com/16398096/99203472-9fffb580-27ed-11eb-8458-fc51bbb15aa8.jpg)

**Comment by osy** [comment]
This is a hardware limitation with non-Mac thunderbolt on Windows and not with OC. People with macbooks without custom apple drivers experience the same issue.
