### ISSUE TITLE
Upgrade to 2.14 failed

### ISSUE THREAD

**Issue by Good0007** [osy/HaC-Mini#381]
**Describe the bug**
     I failed two attempts to upgrade to 2.14,The progress bar finished and auto restarted,I replace it back to 2.13, and then boot to extract the kernel crash information.

**Expected behavior**

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.14
- OSX version [e.g: 10.14.6]: 10.15.7
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: SN750 512G
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: ZHIKE DDR4 2666 16G
- Second DIMM model (if installed): ZHIKE DDR4 2666 16G
- Display port(s) used [e.g: USB-C, mini DP]: mini DP
- Display resolution(s) [e.g: 4K, 5K]: 4K
- Any TB3 devices: 
- Any USB devices: 

**Modifications**

**Panic log**
panic(cpu 4 caller 0xffffff80147719e8): "a freed zone element has been modified in zone kalloc.16: expected 0 but found 0, bits changed 0, at offset 0 of 16 in element 0xffffff8058a7f4e0, cookies 0x3f00118774999aba 0x53521bf59eceb4d"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.2.2/osfmk/kern/zalloc.c:1233
Backtrace (CPU 4), Frame : Return Address
0xffffff83c665b800 : 0xffffff801471868d 
0xffffff83c665b850 : 0xffffff8014852ab5 
0xffffff83c665b890 : 0xffffff801484463e 
0xffffff83c665b8e0 : 0xffffff80146bea40 
0xffffff83c665b900 : 0xffffff8014717d57 
0xffffff83c665ba00 : 0xffffff8014718147 
0xffffff83c665ba50 : 0xffffff8014ebf2bc 
0xffffff83c665bac0 : 0xffffff80147719e8 
0xffffff83c665baf0 : 0xffffff8014771b51 
0xffffff83c665bb20 : 0xffffff801477181c 
0xffffff83c665bb50 : 0xffffff8014772229 
0xffffff83c665bb70 : 0xffffff8014773898 
0xffffff83c665bbb0 : 0xffffff801476fc3f 
0xffffff83c665bce0 : 0xffffff80147255c4 
0xffffff83c665bd50 : 0xffffff8014d94b8c 
0xffffff83c665bd70 : 0xffffff8014d94bfa 
0xffffff83c665bd90 : 0xffffff8014e175ec 
0xffffff83c665bde0 : 0xffffff8014e192c6 
0xffffff83c665be10 : 0xffffff8014e1019c 
0xffffff83c665be60 : 0xffffff8014e0df20 
0xffffff83c665beb0 : 0xffffff8014e1ae78 
0xffffff83c665bee0 : 0xffffff8014e0d8f9 
0xffffff83c665bf30 : 0xffffff8014e2961e 
0xffffff83c665bf70 : 0xffffff8014e28c16 
0xffffff83c665bfa0 : 0xffffff80146be13e 

BSD process name corresponding to current thread: kernel_task
Boot args: alcid=11 agdpmod=ignore -disablegfxfirmware shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2 igfxmetal=1 igfxrpsc=1

Mac OS version:
19H15

Kernel version:
Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64
Kernel UUID: 9B5A7191-5B84-3990-8710-D9BD9273A8E5
Kernel slide:     0x0000000014400000
Kernel text base: 0xffffff8014600000
__HIB  text base: 0xffffff8014500000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 18463500368

**Comment by osy** [comment]
@Good0007 Can you try v2.15?

**Comment by Good0007** [comment]
> @Good0007 Can you try v2.15?

I tried 2.15, but I also reported an error.

panic(cpu 2 caller 0xffffff8001d739d7): "Zone cache element was used after free! Element 0xffffff80435eb5b0 was corrupted at beginning; Expected 0x462a0a56fc9073b3 but found 0; canary 0xb9d5f5d6bfcec603; zone 0xffffff80026a4220 (kalloc.16)"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.2.2/osfmk/kern/zcache.c:658

**Comment by Good0007** [comment]
> > @Good0007 Can you try v2.15?
> 
> I tried 2.15, but I also reported an error.
> 
> panic(cpu 2 caller 0xffffff8001d739d7): "Zone cache element was used after free! Element 0xffffff80435eb5b0 was corrupted at beginning; Expected 0x462a0a56fc9073b3 but found 0; canary 0xb9d5f5d6bfcec603; zone 0xffffff80026a4220 (kalloc.16)"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.2.2/osfmk/kern/zcache.c:658


Good news, I have solved the problem ! Using debug mode, I checked the kernel crash log and found that the crash was due to the installation of incompatible drivers( EasyConnect ,a vpn software).I open config.plist add properties(NVME->ADD->7C436110-AB2A-4BBB-A880-FE41995C9F82->csr-active-config:E7030000)  to disable sip. Now it can start normally. (Can you set this option by default in the configuration?)

**Comment by osy** [comment]
No, to disable SIP follow apple’s instructions. https://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-macos-os-x

**Comment by Good0007** [comment]
> No, to disable SIP follow apple’s instructions. https://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-macos-os-x

Well, thank you very much!
