### ISSUE TITLE
Safe to upgrade to Big Sur?

### ISSUE THREAD

**Issue by hongkongkiwi** [osy/HaC-Mini#382]
Just checking in as I didn't see it mentioned.

Is it safe to upgrade to Big Sur? I've so far been upgrading to Catalina without issues but I'm wondering if I can just click the upgrade button in "Software Update" and it will work as long as I have the latest HaC Mini version installed (?).

**Comment by osy86** [comment]
I had no problems in the beta but I recommend you back up your system beforehand just in case something goes wrong.

**Comment by ikkira** [comment]
![image](https://user-images.githubusercontent.com/4424977/99027197-9dac1a00-25a7-11eb-8662-7f02a50dd014.png)

[#366](https://github.com/osy86/HaC-Mini/issues/316) has been fixed?

**Comment by wangfuco** [comment]
> ![image](https://user-images.githubusercontent.com/4424977/99027197-9dac1a00-25a7-11eb-8662-7f02a50dd014.png)
> 
> [#366](https://github.com/osy86/HaC-Mini/issues/316) has been fixed?

No. Checked in Big Sur 11.0.1, HaCMini v2.14.

**Comment by keatliang2005** [comment]
same here the issue confirm
![Screenshot 2020-11-13 at 2 36 28 PM](https://user-images.githubusercontent.com/473990/99036995-bde6d380-25bd-11eb-838b-a38cbf4dc430.png)
 in public release macOS 11.0.1, with HacMini 2.14

**Comment by Lesinh257** [comment]
![Ảnh chụp Màn hình 2020-11-13 lúc 14 17 29](https://user-images.githubusercontent.com/65233806/99041488-98f26080-25bd-11eb-9787-84c7957f7648.png)
I lost Airdrop feature after going to Big sur 11.0.1 in Catalina it worked perfectly with BCM94360CS2 card

**Comment by billsq** [comment]
Somehow I lost desktop background image... only showing 2 big green squares on a black background.

**Comment by JaySurplus** [comment]
> Somehow I lost desktop background image... only showing 2 big green squares on a black background.

Same here

**Comment by edotyg** [comment]
managed to update with no problem, but the thunderbolt is not identified on my system report

**Comment by StSiem** [comment]
> same here the issue confirm
> ![Screenshot 2020-11-13 at 2 36 28 PM](https://user-images.githubusercontent.com/473990/99036995-bde6d380-25bd-11eb-838b-a38cbf4dc430.png)
> in public release macOS 11.0.1, with HacMini 2.14

Same for me

**Comment by Xuemuyang** [comment]
same

![Uploading image.png…]()

**Comment by bg8erz** [comment]
> Somehow I lost desktop background image... only showing 2 big green squares on a black background.

same with me. do not use desktop with dynamic picture.

**Comment by jomiro19** [comment]
Big Sur 11.0.1 beta worked fine, however when I updated to the release version today it's now in a bootloader that's unrecoverable.

**Comment by kolombet** [comment]
Same story, stuck in boot with the apple logo. Is clear install of bug sur works for anyone?

**Comment by keatliang2005** [comment]
With new 0064 Firmware update, the border render issue seems bit different

![Screenshot 2020-11-17 at 10 04 17 PM](https://user-images.githubusercontent.com/473990/99399669-ef92ce00-2920-11eb-9621-1b9306bf9c95.png)

**Comment by KrisCris** [comment]
The graphics driver seems to have lots of issues currently...

**Comment by domino6789** [comment]
> ![Ảnh chụp Màn hình 2020-11-13 lúc 14 17 29](https://user-images.githubusercontent.com/65233806/99041488-98f26080-25bd-11eb-9787-84c7957f7648.png)
> I lost Airdrop feature after going to Big sur 11.0.1 in Catalina it worked perfectly with BCM94360CS2 card

Hello, Are you upgrade to 11.0.1 with OTA or Clean install? I'm using HacMini v2.14 and clean install big sur 11.0.1 and have issue reboot go to recovery after install BigSur. Please let me know if you have same issue. Thank you from Vietnam.

**Comment by Lesinh257** [comment]
> > ![Ảnh chụp Màn hình 2020-11-13 lúc 14 17 29](https://user-images.githubusercontent.com/65233806/99041488-98f26080-25bd-11eb-9787-84c7957f7648.png)
> > I lost Airdrop feature after going to Big sur 11.0.1 in Catalina it worked perfectly with BCM94360CS2 card
> 
> Hello, Are you upgrade to 11.0.1 with OTA or Clean install? I'm using HacMini v2.14 and clean install big sur 11.0.1 and have issue reboot go to recovery after install BigSur. Please let me know if you have same issue. Thank you from Vietnam.

I upgrade OTA, if you get boot error, re-plug the bootable USB into MAC and reinstall the latest version HacMinni into your MAC drive.
