### ISSUE TITLE
Can't enable 144hz on the monitor when FreeSync is enabled

### ISSUE THREAD

**Issue by JerryXu-code** [osy/HaC-Mini#397]
- HaC Mini version:v2.14 
- OSX version:11.0.1 beta
- NUC model:NUC8i7HVK
- Boot SSD model and protocol:Hikvision C2000 Pro 
- Display port(s) used :mini DP 
- Display resolution(s):3440x1440,144hz 
- No modification to EFI

I *can't* use 144hz on Big sur.I can use 144hz on Windows 10 and Catalina.
But when I update to 11.0.1 beta,I just can't use 144hz.
And what happened to the window?
![image](https://user-images.githubusercontent.com/67638117/100084620-f45a0380-2e85-11eb-9091-6814e343bed7.png)

**Comment by PumaOsX** [comment]
Just download (https://github.com/osy86/HaC-Mini/files/5579485/Polaris22Fixup.kext.zip), then...download Clover Configurator (find the last global version on mackie100projects) open it, find the voice mount EFI on the left, select your macOS drive and select mount EFI, then select open EFI and go in the kext folder under OC folder and past the Polaris22Fixup.kext overwriting the old one... it's possible you need to insert your password to approve the copy.
Reboot and done.

**Comment by osy** [comment]
I think this would be an issue with OSX's driver.

**Comment by JerryXu-code** [comment]
> I think this would be an issue with OSX's driver.

umm...Will this better with HaC-Mini v2.15?

**Comment by osy** [comment]
Seems like people are running into this on Macs as well https://forums.macrumors.com/threads/4k-144hz-no-longer-working-after-update.2267913/

**Comment by JerryXu-code** [comment]
Still can't enable 144hz,even update to 11.1.i installed 11.1 for 3 times,but there's only one time that i can enable 144hz.

**Comment by JerryXu-code** [comment]
Now i can enable 144hz after disable Freesync,but for some reasons(idk why)sometimes i can't enable 144hz when FreeSync is disabled

**Comment by osy** [comment]
Can you test on a real Macbook? I think this is an AMD driver issue.

**Comment by JerryXu-code** [comment]
> Can you test on a real Macbook? I think this is an AMD driver issue.

Nope,'cause I don't have a Macbook:(

**Comment by osy** [comment]
Closing since I believe it’s a macos issue. Feel free to reopen if you can test it on a Mac and that’s not the case.
