### ISSUE TITLE
Bluetooth non connected before login

### ISSUE THREAD

**Issue by Alisouu** [osy/HaC-Mini#456]
Hello,
I can't use my Apple Magic Keyboard 2 to login on the macOS.
My Filevault is enabled and i think that the Bluetooth work only after the login.

I want to know if there is a solution.

Thank you.

**Configuration**
- HaC Mini version : v2.14
- OSX version : 10.15.7
- NUC model : NUC8i7HNK
- Wi-Fi/Bluetooth devices : DW1820A CN-08PKF4

**Comment by Malumen** [comment]
@Alisouu IIRC this is a known problem with FileVault and other macOS security measures with Bluetooth. Are you using Intel Bluetooth kext or have you replaced with your own m.2 module?

**Comment by osy** [comment]
Only official Apple card have 100% support.
