### ISSUE TITLE
Dark wallpapers still not working with Polaris Kext Fix

### ISSUE THREAD

**Issue by nach0boss** [osy/HaC-Mini#459]
**Describe the bug**
After applying the Polaris22fix Kext, the rounded corners are fixed and wallpapers can be set. However, the Dark Wallpaper still produce a black background with green artefacts.

**Expected behavior**
Dark wallpaper set

**Configuration**
- HaC Mini version: 2.1.4
- OSX version: 11.0.1 
- NUC model: NUC8i7HNK

**Modifications**
https://github.com/osy86/HaC-Mini/issues/316#issuecomment-736083144

**Comment by HiMetre** [comment]
do you checked SetCodecAMD while install hac-mini.pkg, and disable intel gpu in bios?
try enable intel gpu in bios.

**Comment by osy** [comment]
@nach0boss Please try v2.15

**Comment by goodbest** [comment]
If the wallpaper still has green blocks and black background after installing 2.15, 
Try the following two methods to see if that helps:
- change to another background wallpaper, and reboot.
- try remove the following cache file, and reboot.
 `/Library/Caches/Desktop Pictures/<some random uuid>/lockscreen.png

**Comment by nach0boss** [comment]
> @nach0boss Please try v2.15

After 2.15 update I cant boot into

**Comment by evil4blue** [comment]
I know this issue was closed, but I'm still having the same problem.  I've trued the suggestions in this thread, but certain wallpapers are still corrupted with green squares and none of the transition backgrounds actually transition.  Seem like all the other graphics glitches were fixed with the polaris22 fix up.

**Comment by Oosram** [comment]
> I know this issue was closed, but I'm still having the same problem. I've trued the suggestions in this thread, but certain wallpapers are still corrupted with green squares and none of the transition backgrounds actually transition. Seem like all the other graphics glitches were fixed with the polaris22 fix up.

me too, still the same

**Comment by Oosram** [comment]
after upgrade to 11.1, the green squares are gone, only left with none transition for third party HEIC wallpaper @evil4blue

**Comment by osy** [comment]
Closing since it seems like it’s fixed in 11.1
