### ISSUE TITLE
After upgrading to 2.1.5, Boot Picker cannot use the mouse

### ISSUE THREAD

**Issue by alenzhong** [osy/HaC-Mini#462]
Describe the bug
After upgrading to 2.1.5, Boot Picker cannot use the mouse
logitech MX ANYWHERE 2 or other usb mouse，Can't show use。
-------------------------------------------
HaC Mini version 2.1.5 
OSX version 10.15.7 
NUC model NUC8i7HVK
Boot SSD model and protocol : Western Digital SN750 1T
Second SSD model and protocol : Intel 760P 512G
First DIMM model : Kingston Hyperx IMPACT DDR4-2666 16GB X 2 
Display port(s) used mini DP
Any Wi-Fi/Bluetooth devices :DW1820A
mouse：logitech MX ANYWHERE 2
Connection method：Logitech Unifying Receiver

**Comment by keatliang2005** [comment]
from the 0.6.4 changelog i think there is new config variable need to added
- Made pointer control optional for OpenCanopy via PickerAttributes

from OC doc
0x0010 — OC_ATTR_USE_POINTER_CONTROL, enable pointer control in the picker when available. For example, this could make use of mouse or trackpad to control UI elements.

**Comment by alenzhong** [comment]
Can be set with QtOpenCoreConfig
