### ISSUE TITLE
WindowServer Kernel Panic - HaC Mini v2.15

### ISSUE THREAD

**Issue by rolsanmordua** [osy/HaC-Mini#467]
**Describe the bug**
Leaving my machine idle overnight after turning off monitors results to machine being turned off after kernel panic. I have reproduced 2 nights in a row since updating. 

**Expected behavior**
No reboots overnight when idle. 

**Configuration**
- HaC Mini version [e.g: 2.0]: v2.15
- OSX version [e.g: 10.14.6]: 10.15.7
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: WD Black SN750 1 TB [NVMe]
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: ADATA SX8200 1 TB [NVMe] for Windows but never used
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Samsung DDR4-2666 32 GB
- Second DIMM model (if installed): Samsung DDR4-2666 32 GB
- Display port(s) used [e.g: USB-C, mini DP]: N/A
- Display resolution(s) [e.g: 4K, 5K]: 3 x 4K monitors (scaled to 5K in macOS) via eGPU
- Any TB3 devices: Sonnet Breakaway Box 550 powering 3x 4K monitors
- Any USB devices: mouse, keyboard
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: BCM94352Z

**Modifications**
List any mods to `config.plist`, any additional kexts, anything installed to `/Library/Extensions` and `/System/Library/Extensions`, any additional patches, etc. Please attach your `config.plist` if you made any modifications.
N/A

**Panic log**
Include a screenshot of the panic message if applicable.

```
panic(cpu 2 caller 0xffffff7f82738ad5): userspace watchdog timeout: no successful checkins from com.apple.WindowServer in 120 seconds
service: com.apple.logd, total successful checkins since load (53561 seconds ago): 5357, last successful checkin: 0 seconds ago
service: com.apple.WindowServer, total successful checkins since load (53531 seconds ago): 5336, last successful checkin: 120 seconds ago

Backtrace (CPU 2), Frame : Return Address
0xffffffa77d32b720 : 0xffffff800151a65d 
0xffffffa77d32b770 : 0xffffff8001654a75 
0xffffffa77d32b7b0 : 0xffffff80016465fe 
0xffffffa77d32b800 : 0xffffff80014c0a40 
0xffffffa77d32b820 : 0xffffff8001519d27 
0xffffffa77d32b920 : 0xffffff800151a117 
0xffffffa77d32b970 : 0xffffff8001cc1ad8 
0xffffffa77d32b9e0 : 0xffffff7f82738ad5 
0xffffffa77d32b9f0 : 0xffffff7f827387fa 
0xffffffa77d32ba10 : 0xffffff8001c5397e 
0xffffffa77d32ba60 : 0xffffff7f82737cfe 
0xffffffa77d32bb60 : 0xffffff8001c5cba3 
0xffffffa77d32bca0 : 0xffffff80016035e2 
0xffffffa77d32bdb0 : 0xffffff80015203c8 
0xffffffa77d32be10 : 0xffffff80014f6d15 
0xffffffa77d32be70 : 0xffffff800150db22 
0xffffffa77d32bf00 : 0xffffff800162c065 
0xffffffa77d32bfa0 : 0xffffff80014c1226 
      Kernel Extensions in backtrace:
         com.apple.driver.watchdog(1.0)[B6A95892-6C75-3CF5-A6CC-6D83F30FA1D5]@0xffffff7f82737000->0xffffff7f8273ffff

BSD process name corresponding to current thread: watchdogd
Boot args: alcid=11 agdpmod=ignore -disablegfxfirmware shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2 igfxmetal=1

Mac OS version:
19H2

Kernel version:
Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64
Kernel UUID: 05D51A3D-3A87-3FF0-98C3-9CF3827A3EDD
Kernel slide:     0x0000000001200000
Kernel text base: 0xffffff8001400000
__HIB  text base: 0xffffff8001300000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 53591928463634
```

Some reports of this occurring on real Macs with external monitors when idle: 
[https://discussions.apple.com/thread/251234777](https://discussions.apple.com/thread/251234777)
[https://discussions.apple.com/thread/250715149](https://discussions.apple.com/thread/250715149)

**Comment by osy** [comment]
Can you try having your display connected directly and not through the thunderbolt box? I think it’s an issue with thunderbolt. On my 2016 MBP I constantly ran into KP overnight when I had a display plugged in to thunderbolt.

**Comment by rolsanmordua** [comment]
It works directly via HDMI but the whole reason I have the eGPU setup is because I'm driving 3x 4K displays (scaled at 5K). What is the downgrade process? Can I just reinstall v2.14 after installing v2.15?

**Comment by rolsanmordua** [comment]
Would downgrading WhateverGreen or PolarisFixup help at all? It was stable on v2.14.

**Comment by osy** [comment]
You can reinstall 2.14 to downgrade. Alternatively you can replace the WhateverGreen kext from v2.14. But if it’s an issue please report it so it can be fixed.

**Comment by osy** [comment]
@rolsanmordua Did you ever determine if it was WhateverGreen update that was the issue or not?

**Comment by rolsanmordua** [comment]
@osy I reinstalled with most recent installer and haven't had issues since but I'm out of town and won't get back to my machine until early January to do further testing.

**Comment by rolsanmordua** [comment]
Haven't been able to reproduce since. Running latest v2.15 with no other changes
