### ISSUE TITLE
Update to 11.1 (not a bug)

### ISSUE THREAD

**Issue by JaseNZC** [osy/HaC-Mini#471]
<img width="591" alt="Screen Shot 2020-12-15 at 8 11 17 PM" src="https://user-images.githubusercontent.com/64925341/102182846-cfe7c900-3f11-11eb-8544-f344aa67ae79.png">

Just wanted to say upgraded this morning to 11.1 running version 2.15 and had zero issues :-)

**Comment by Oosram** [comment]
does your wallpaper working properly?

**Comment by JaseNZC** [comment]
Yes no problems with graphics at all that I have come across and been using it all day now. :-)

**Comment by Oosram** [comment]
how did you upgrade from Catalina？new install Big Sur？

**Comment by JaseNZC** [comment]
This was a new install of Big Sur about 4 or 5 days ago then they released this update so went from 11 to 11.1

**Comment by keatliang2005** [comment]
> how did you upgrade from Catalina？new install Big Sur？

Just perform update install like on real mac

mine 11.0.1 to 11.1 no issue

**Comment by Oosram** [comment]
after upgrade to 11.1, the green squares are gone, only left with none transition for third party HEIC wallpaper

**Comment by YucongDing** [comment]
> how did you upgrade from Catalina？new install Big Sur？

Directly upgrade from macOS Catalina, and everything runs well.
