### ISSUE TITLE
TB3 hybrid ACPI implementation

### ISSUE THREAD

**Issue by Charlyo** [osy/HaC-Mini#519]
Dear Osy,

Thank you for this amazing guide! 

Looking at https://osy.gitbook.io/hac-mini-guide/details/thunderbolt-3-fix-part-2, it seems that at some point, before going patching the tb3 firmware, you actually had an hybrid implementation using the oem tb3 firmware.

Currently I have a T480 and I would be interested in replicating that approach in order to see If I could obtain thunderbolt bus working. I'm aware of all the caveats of having that implementation.

Is there any commit that I could follow prior you having flashed the firmware?? 
Thanks in advance!

**Comment by osy** [comment]
https://github.com/osy/HaC-Mini/blob/master/ACPI/SSDT-TbtLegacy.asl and related files.

**Comment by Charlyo** [comment]
Thank you! 

Just to be 100% clear, only : 

SSDT-TbtLegacy.asl,  SSDT-TbtLegacy-Boot.asl and  SSDT-TbtLegacy-Power.asl ??

**Comment by osy** [comment]
Yes, the comments + the article should provide you with the background of what each part is for.

**Comment by Charlyo** [comment]
Perfect! Thank you very much!
