### ISSUE TITLE
Bigsur Opencore USB won't boot. 

### ISSUE THREAD

**Issue by unsungloser** [osy/HaC-Mini#520]
Bigsur installer made in Mac OS. Hac-mini pkg installed without patcher because it's greyed out for bigsur. Opencore shows up in bootmenu but on pressing enter it goes back to the boot menu. Doesn't boot from opencore. Secure boot as instructed is disabled. 
USB drive is 3.0 and i am trying to install through the blue usb port on the front. Installation options left at default except adding show boot menu to the installer. 

**Expected behavior**
Opencore booting and allowing me to select Bigsur installation.

**Environment:**
 - HaC Mini installer version: 2.15
 - BIOS Version HN0063

**Additional context**
USB boots okay on my hackintosh ideapad 330s 15iKB. Changed around USB ports on the hades canyon but no effect. Shows up on boot selector but never opens up.

**Logs**
No logs since open core never boots. 

https://user-images.githubusercontent.com/76798784/103390361-40294980-4ad1-11eb-9aee-b556ebcb97e4.mov

**Comment by osy** [comment]
You need to reset your BIOS. OpenCore should NOT be listed as an option. You should see an option for your USB drive (Part 0) instead. Make sure OpenCore is not installed on your SATA or NVMe drives.

When OpenCore shows up as a named option, that means the EFI firmware was told to boot from a specific path that may be invalid.

**Comment by unsungloser** [comment]
Thanks. Issue resolved. I nuked my drives and started fresh. I bought this NUC off eBay. It seems like the previous owner had installed hackintosh w/ boot camp and then tried to get rid off it. There was open core installed on the drive.

**Comment by ednitworld** [comment]
> You need to reset your BIOS. OpenCore should NOT be listed as an option. You should see an option for your USB drive (Part 0) instead. Make sure OpenCore is not installed on your SATA or NVMe drives.
> 
> When OpenCore shows up as a named option, that means the EFI firmware was told to boot from a specific path that may be invalid.

i have same issue, but i cant find any solution, i am using gigabyte z790 UD Motherboard, im installion first time hackintosh on this pc, please get me some solution.
