### ISSUE TITLE
Unable boot from installer

### ISSUE THREAD

**Issue by ZeroClover** [osy/HaC-Mini#522]
**Describe the bug**
Following the installation guide process, I formatted the USB device with an HFS+ file system and a GUID partition map.

Then run the following command to create the macOS installation.

`sudo "/Applications/Install macOS Big Sur.app/Contents/Resources/createinstallmedia" --volume /Volumes/Installer`

Once created, run HaCMini.pkg and set the installation target to USB macOS installer.

After everything was done, I connected the USB to the NUC and powered it on, but the NUC showed "A bootable device has not been detected."

The latest BIOS has been flashed for the NUC, and the BIOS has been set up according to the pre-installation guidelines.

**Expected behavior**
Go to the macOS installer.

**Environment:**
 - Running OSX version: macOS 11.1 Big Sur
 - Target drive OSX version: macOS 11.1 Big Sur
 - HaC Mini installer version: 2.15

**Additional context**

After the Intel NUC Logo appears on boot and press F10 to enter the boot selection menu, I can see the OpenCore boot item. After selecting this boot item, it will go back to the boot selection menu again and cannot enter the macOS installer.

There are two NVMe SSDs installed in the NUC, the Samsung 960 Pro and the SN550, with no partitions or content contained in the SSDs.

**Logs**
There are no logs because there is not even access to the installer.

**Comment by osy** [comment]
> I can see the OpenCore boot item

That’s wrong. You have some older installation that’s messing things up. Reset your BIOS and make sure your drivers are clean. See #520

**Comment by ZeroClover** [comment]
@osy 

I have tried resetting the BIOS using the following methods.

1. select Load Default in vBIOS
2. Remove the BIOS security jumper and select "BIOS Recovery."
3. Use the power button menu and then select "BIOS Recovery."

But it doesn't work, and I still can't get to OpenCore.

The USB device shows up as a separate OpenCore boot item in the boot menu in F10, and in vBIOS, it shows up as "UEFI: USB: OpenCore: PART 0: Bootloader."

![image](https://user-images.githubusercontent.com/13190004/103522692-b1904000-4eb5-11eb-857b-bdf93f7f7b99.png)

I also tried completely formatting the NVMe drive installed in the NUC, such as booting Windows PE to format the drive and even installing Windows on it to try to destroy the EFI partition that might contain other OpenCore.

**Comment by ZeroClover** [comment]
Attempts to reset NUC NVRAM have failed, and multiple similar issues can be found in the Intel forums (BIOS memorized invalid boot items).

Finally, I reinstalled Windows 10, then used bcdedit to remove multiple invalid OpenCore boot entries, and then restarted the NUC.

There is still only a separate OpenCore option in the boot menu. Still, this time, selecting the OpenCore entry and press the Option key allowed me to enter the OpenCore menu and install macOS properly.
