### ISSUE TITLE
[Discussion] Safe to upgrade to Big Sur?

### ISSUE THREAD

**Issue by KrisCris** [osy/HaC-Mini#526]
Guys,

How well is Big Sur supported by HacMini compared to Catalina?
Does any major function missing?

**Comment by mr-vito** [comment]
I think it comes down to whether you actually need Big Sur (e.g. compatibility with some apps or newer versions such as Safari!). 

I have the following problems to date on 11.1: 
- System will not wake from sleep when locked;
- Screen flickering with a 4K60 HDMI 2.1 monitor

Overall, they both relate to the updated Polaris22FixUp/WhateverGreen kext.

I am pretty sure they will be solved shortly.

A part from the above, everything works IMO more or less consistently.

**Comment by kingrhy** [comment]
I notice this pkg still cannot patch 11.0.1 or 11.1 installation disk. do we have resolve this issue so far?

**Comment by kingrhy** [comment]
and after install 10.15.  there is no sound . how I can fix it? 10.14.x  is working good.

**Comment by KrisCris** [comment]
@kingrhy 
I think the sound works just fine in 10.15... Did you select the correct output device?

**Comment by kingrhy** [comment]
@KrisCris I do not know. but I have notice it work good when I use Clover.  currently I use OC  and it cannot work.
I guess kext or driver not install corrctly.   BTW: there is no any output device I can select in options.  I can upload some video tommorrow  .could you give some comments which options I have to check and take some video for further troubleshoot? thank you very much

**Comment by JaseNZC** [comment]
For a few bucks I just use a usb audio device, never have to worry about anything and it just works every time.

I get the screen flicker on my LG 4K monitor be it hdmi or the usb c output. Its not a major or deal breaker for me as I just use mine for mucking around anyway and have a macbook pro for my dedicated work.

Apart from that everything just works without an issue.

**Comment by KrisCris** [comment]
> @KrisCris I do not know. but I have notice it work good when I use Clover. currently I use OC and it cannot work.
> I guess kext or driver not install corrctly. BTW: there is no any output device I can select in options. I can upload some video tommorrow .could you give some comments which options I have to check and take some video for further troubleshoot? thank you very much

Honestly idk, perhaps you need to open a new issue letting osy know about this...

**Comment by KrisCris** [comment]
> I think it comes down to whether you actually need Big Sur (e.g. compatibility with some apps or newer versions such as Safari!).
> 
> I have the following problems to date on 11.1:
> 
> * System will not wake from sleep when locked;
> * Screen flickering with a 4K60 HDMI 2.0 monitor
> 
> Overall, they both relate to the updated Polaris22FixUp/WhateverGreen kext.
> 
> I am pretty sure they will be solved shortly.
> 
> Apart from the above, everything works IMO more or less consistently.

Yea, I saw some graphics related issues been reported before, unsure whether they have been resolved. Maybe I need to wait for a longer time and see...

**Comment by murphycn** [comment]
> I notice this pkg still cannot patch 11.0.1 or 11.1 installation disk. do we have resolve this issue so far?

I've same problem, do you solve it?

**Comment by osy** [comment]
You don’t need to patch the installer. It was just a convenience. Follow the updated instruction on gitbook.

**Comment by leedashone** [comment]
For me, Upgrade to 11.0 is fine, but video file thumbnail can't display correct,
However after upgrade to 11.1 this bug recovered!  Everything is ok.
Then I upgrade to 11.2 also no problem!

**Comment by osy** [comment]
Closing since Big Sur is working fully.
