### ISSUE TITLE
REQUEST: Change Optional "Intel Wireless" Option (to v 1.2.0 STABLE)

### ISSUE THREAD

**Issue by Malumen** [osy/HaC-Mini#528]
Hello!

Version 1.2.0 `STABLE` of zxystd's [OpenIntelWireless project](https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.2.0) has been released and rolls up the Itlwmx and Itlwm into one kext, no longer requires HeliPort for use. Still does not allow true Apple Watch unlock or AirDrop, has some limitations for WiFi protocol, but it is better than nothing! (now supports WPA2, among other features)

Note: at the rate `STABLE` versions get released, you likely won't be updating this anytime soon...

**Comment by osy** [comment]
@Malumen did you test the PR yet?

**Comment by Malumen** [comment]
> @Malumen did you test the PR yet?

Sorry what exactly do you mean?

**Comment by osy** [comment]
https://github.com/osy/HaC-Mini/suites/1846290716/artifacts/35760088

**Comment by Malumen** [comment]
@osy Thank you! I will try when I am able ASAP

**Comment by Malumen** [comment]
Hi @osy !

After needing to take this thing around to various locations (long story), I can confirm the WiFi works OK! It is not the fastest speeds, but it is very good!

I would totally recommend incorporating [itlwm 1.2.0](https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.2.0) into the project!
