### ISSUE TITLE
H.264/265 hardware Encoder/Decoder can't work

### ISSUE THREAD

**Issue by leedashone** [osy/HaC-Mini#531]
**Describe the bug**
Maybe it's not a bug, but the onboard hardware H.264/265 Encoder/Decoder
from AMD Vega M GL can't work. 

**Expected behavior**
I try two video transcode software: HandBrake & VideoProc, 
both Apps can't enable hardware encoder.
I also try "moonlight client ", it also say "No h.264 hardware decoder found"

**Configuration**
- HaC Mini version [e.g: 2.0]: v2.16
- OSX version [e.g: 10.14.6]: 11.1
- NUC model [e.g: NUC8i7HNK]: NUC8I7HNK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: UMAX M800 1TB NvME SSD
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]:  N/A
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: UMAX DDR4-2666 16GB
- Second DIMM model (if installed): UMAX DDR4-2666 16GB
- Display port(s) used [e.g: USB-C, mini DP]: N/A
- Display resolution(s) [e.g: 4K, 5K]: 4K (via HDMI port)
- Any TB3 devices: N/A
- Any USB devices: Mouse & Keyboard & USB Speaker
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: N/A

**Modifications**
None

**Panic log**
Include a screenshot of the panic message if applicable.
<img width="529" alt="Moonlight" src="https://user-images.githubusercontent.com/8998018/105197791-f4ba0680-5b77-11eb-98c1-8cbad2e7a260.png">
<img width="847" alt="VideoProc" src="https://user-images.githubusercontent.com/8998018/105197807-f84d8d80-5b77-11eb-9300-79ea36c0d341.png">
<img width="884" alt="HandBrake" src="https://user-images.githubusercontent.com/8998018/105197818-fb487e00-5b77-11eb-96fd-adee34992b5a.png">

**Comment by osy** [comment]
Did you select the AMD encoder option in the HaC mini installer?

**Comment by leedashone** [comment]
Thanks for reply.
I install my system about 6 months.  At first time I am use Intel codec.
And hardware codec won't work.
Few days ago I install HaCMini again, and select AMD codec,, 
After install I reboot system,, hardware code still not work.
I try many times, the hardware encoder still can't work.
<img width="616" alt="Hardware Codec" src="https://user-images.githubusercontent.com/8998018/105360267-5e4b1b00-5c33-11eb-836a-5fa8f11949dd.png">

**Comment by gotschi** [comment]
works fine for me

**Comment by SingSky** [comment]
HaC Mini version [e.g: 2.0]: v2.16
OSX version [e.g: 10.14.6]: 10.15.7
NUC model [e.g: NUC8i7HNK]: NUC8I7HNK
Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Intel 256G NVME SSD
Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: N/A
First DIMM model [e.g: Patriot DDR4-2666 16GB]: SAMSUNG DDR4-3200 8GB
Second DIMM model (if installed): SAMSUNG DDR4-3200 8GB
Display port(s) used [e.g: USB-C, mini DP]: MiniDP to DP 
Display resolution(s) [e.g: 4K, 5K]: 4K 
Any TB3 devices: N/A
Any USB devices: Mouse & Keyboard 
Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: BCM94360CS2

Same bug here, I have tried Intel and AMD Encoder from new installation but both H264/H265 hardware Encoder didn't work in VideoProc.

**Comment by wuhouhongcha** [comment]
> **Describe the bug**
> Maybe it's not a bug, but the onboard hardware H.264/265 Encoder/Decoder
> from AMD Vega M GL can't work.
> 
> **Expected behavior**
> I try two video transcode software: HandBrake & VideoProc,
> both Apps can't enable hardware encoder.
> I also try "moonlight client ", it also say "No h.264 hardware decoder found"
> 
> **Configuration**
> 
> * HaC Mini version [e.g: 2.0]: v2.16
> * OSX version [e.g: 10.14.6]: 11.1
> * NUC model [e.g: NUC8i7HNK]: NUC8I7HNK
> * Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: UMAX M800 1TB NvME SSD
> * Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]:  N/A
> * First DIMM model [e.g: Patriot DDR4-2666 16GB]: UMAX DDR4-2666 16GB
> * Second DIMM model (if installed): UMAX DDR4-2666 16GB
> * Display port(s) used [e.g: USB-C, mini DP]: N/A
> * Display resolution(s) [e.g: 4K, 5K]: 4K (via HDMI port)
> * Any TB3 devices: N/A
> * Any USB devices: Mouse & Keyboard & USB Speaker
> * Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: N/A
> 
> **Modifications**
> None
> 
> **Panic log**
> Include a screenshot of the panic message if applicable.
> <img alt="Moonlight" width="529" src="https://user-images.githubusercontent.com/8998018/105197791-f4ba0680-5b77-11eb-98c1-8cbad2e7a260.png">
> <img alt="VideoProc" width="847" src="https://user-images.githubusercontent.com/8998018/105197807-f84d8d80-5b77-11eb-9300-79ea36c0d341.png">
> <img alt="HandBrake" width="884" src="https://user-images.githubusercontent.com/8998018/105197818-fb487e00-5b77-11eb-96fd-adee34992b5a.png">
![image](https://user-images.githubusercontent.com/44316609/107741644-86b4c980-6d48-11eb-9066-9145e27765de.png)
First, you need to set intel's built-in display to Disable inside the BIOS.
Second, after you open VideoProc, you need to click Refresh on the right side for the status to become available. However, HEVC mode is still not available.

I also encountered these problems you mentioned, tried many times, only to find that I did not click the refresh button, it is too inconspicuous, try it, good luck!

**Comment by wuhouhongcha** [comment]
![image](https://user-images.githubusercontent.com/44316609/107845529-14f78100-6e17-11eb-9cbd-fbb57f59fe19.png)
When I am in the BIOS, the intel built-in graphics card forced to turn on, meaning "enable", HEVC can work properly.

**Comment by SingSky** [comment]
Thanks for @wuhouhongcha 's help, the key point is not refresh buttons but the BIOS settings. I checked my BIOS settings and changed "Intel iGD" from "Auto" to "Enable", now H264/265 works with Intel hardware encoder selected!

<img width="880" alt="Screenshot 2021-02-16 at 5 07 28 PM" src="https://user-images.githubusercontent.com/11588002/108041972-3310eb80-707a-11eb-8b49-12d1c2f2837d.png">

**Comment by leedashone** [comment]
Thanks @wuhouhongcha ,, Enable Intel IGP in BIOS as default also work for me! 

But the transcoder performance is not so good.
In my case NUC8I7HNK convert FHD-60fps-h264 videos to FHD-30fps-h265-2000K only got 45fps.
My second PC (AMD 4800, NV2070) can got 120fps.

The VideoProc can use hardware encoder too.   
(However moonlight client still say no hardware encoder found,, but software decoder good enough so it's ok)

**Comment by leedashone** [comment]
Hi guys, this issue is gone! Enable Intel IGP in BIOS is the solution to have hardware 26/265 encoder. Special Thanks to @wuhouhongcha for help. Happy Hackintosh.
