### ISSUE TITLE
[INFO] How to Fix broken display after upgrade to Big Sur 11.3 beta(20E5172i)

### ISSUE THREAD

**Issue by havvk** [osy/HaC-Mini#537]
After upgrade to Big Sur 11.3 beta(20E5172i), the broken display issue appears again.

We can fix it by the following steps until osy releases a new version.
**WARNING: have a good backup and plan to erase and reinstall your Mac from the internet before trying this procedure. A mistake can prevent your system from starting without assistance.**

Download AMD Driver from: [AMDMTLBronzeDriver.bundle.zip](https://github.com/osy86/HaC-Mini/files/5268614/AMDMTLBronzeDriver.bundle.zip), the extract it to disk.
```
Disable FileVault.
Reboot into recovery mode and run:
csrutil authenticated-root disable

Reboot back into MacOS.
Find your root mount's device - run mount and chop off the last s, e.g. if your root is /dev/disk1s2s3, you'll mount /dev/disk1s2.
Create a new directory, for example ~/mount.
Run sudo mount -o nobrowse -t apfs <DISK_PATH> <MOUNT_PATH>, using the values from above.
( for example: sudo mount -o nobrowse -t apfs /dev/disk2s5 ~/mount )

sudo cp ~/Downloads/AMDMTLBronzeDriver ~/mount/System/Library/Extensions/AMDMTLBronzeDriver.bundle/Contents/MacOS/

Run sudo bless --folder <MOUNT_PATH>/System/Library/CoreServices --bootefi --create-snapshot
( for example: sudo bless --folder ~/mount/System/Library/CoreServices --bootefi --create-snapshot )

Reboot your system, and the changes will take place.
```
reference information: https://apple.stackexchange.com/questions/395508/can-i-mount-the-root-system-filesystem-as-writable-in-big-sur

**Comment by keatliang2005** [comment]
oh my broken again ? do you have some screenshot ? border issue again

**Comment by goodbest** [comment]
Try this kext with 11.3 beta.
[Polaris22Fixup.kext.zip](https://github.com/osy/HaC-Mini/files/5988570/Polaris22Fixup.kext.zip)

So you don't have to put the old AMDMTLBronzeDriver.bundle back to your system.
