### ISSUE TITLE
When booting installer usb, screen flashes black shortly and returns to UEFI boot menu

### ISSUE THREAD

**Issue by ChupaCobra** [osy/HaC-Mini#539]
I am trying to run the installation guide, using a NUC8i7HNK2 (manufacturing date 12/2020). Bios is updated to latest (0064).
Followed the installation guide to the dot, after resetting and adjusting bios settings according to the guide, but got stuck at Installing macOS.
After inserting the installer usb and selecting it (labeled OpenCore) from the UEFI boot menu, the screen flashes black shortly and returns to the UEFI boot menu.
It seems like OpenCore and/or the installer don't even get the chance to load.

Tried with both Catalina and Big Sur.
Tried several usb sticks.
Even tried on another NUC (same version).
All with the same outcome.

Am I missing something here? 

If you need any aditional information, please let me know.

**Comment by osy** [comment]
Format your SSD and reset your BIOS. You probably have an old/broken OC installed.

**Comment by ChupaCobra** [comment]
I formatted and reset the BIOS (using F9 in BIOS; are there better ways?). This did not work. 
However, I read somewhere, that someone tried something similar and used 2 USB sticks. The first one still gets recognised/labeled as OpenCore. The other is labeled correctly though, and can be used to install.
I am currently;y happily typing this from my HaC-mini.

Many thanks for the comprehensive guide and nudging me in the right direction with this issue.

**Comment by AppleTechy** [comment]
@ChupaCobra I am experiencing the same issue. Do you have a link the resource you used to fix the problem? Wish  I had read the closed problems early since I spent the past 4 hours reformatting and trying different usb sticks and ports.

**Comment by AppleTechy** [comment]
@osy Do you have any idea what OP was talking about with using 2 usb sticks to install? I couldn't find anything on Google or reddit.

**Comment by ChupaCobra** [comment]
> @ChupaCobra I am experiencing the same issue. Do you have a link the resource you used to fix the problem? Wish I had read the closed problems early since I spent the past 4 hours reformatting and trying different usb sticks and ports.

Hi @AppleTechy,

Unfortunately, I do not remember the link/topic where I found this information.
I literally created 2 installer USB sticks and inserted both in the nuc at the same time. While one was not correctly recognized by the bios/UEFI, the other was, so installation succeeded.

**Comment by AppleTechy** [comment]
@ChupaCobra, I couldn't get your trick using 2 installer USB sticks to work. However, I was able to get into opencore by using the trick that was mentioned in Discussion #955  by using the builtin UEFI shell and manually running the OpenCore bootloader. Every reboot since I have not had to manually run the .efi file even with having performed multiple erases of the usb stick.
