### ISSUE TITLE
Please update installation guide about wifi

### ISSUE THREAD

**Issue by mtdcy** [osy/HaC-Mini#541]
There is a M2/NGFF wifi chip named BCM94352Z than can be used to replace original one without adaptor. It works perfect.

**Comment by Medizinmann-MD** [comment]
An even better/faster solution are cards using BCMBCM94360NG - with speeds up to 1200Mbps - and of course also no extra adapter needed.
Availability is good and prices start around $42 on eBay and AliExpress + $10-$15 more on Amazon...

It has been discussed in this thread…
https://github.com/osy/HaC-Mini/issues/191

**Comment by Iaroslav-M** [comment]
So, both BCM94352Z and BCMBCM94360NG don't need any wires? 
--



--

**Comment by Medizinmann-MD** [comment]
> ## So, both BCM94352Z and BCMBCM94360NG don't need any wires?
> --

You don't need an extra adapter NGFF to M.2 as for the cards with BCM94360CS2...
https://osy.gitbook.io/hac-mini-guide/post-installation/wifi#requirements

...so you can still use the 2nd M.2 and no mod on the case is needed.

But of course you must connect it to the WiFi/Bluetooth antennas of you HaC - but you can just use the exiting cables - no extra wires needed.

**Comment by immie-jay** [comment]
Please add that Airdrop works as well

**Comment by Medizinmann-MD** [comment]
> Please add that Airdrop works as well

Yepp, AFAIK everything (WiFi, Bluetooth, Airdrop, Handoff etc.) works as these Broadcom-Chipsets are supported natively by MacOS. I personally only use WiFi & Bluetooth (with Magic Trackpad, Headsets etc.) – as I don’t own an iPhone -  so I didn't test Handoff/Airdrop so far.

**Comment by immie-jay** [comment]
Unlocking with Apple Watch or iPhone also works - most times. Appears erratic

I have the BCMBCM94360NG card

**Comment by Medizinmann-MD** [comment]
> Unlocking with Apple Watch or iPhone also works - most times. Appears erratic
> 
> I have the BCMBCM94360NG card

Which MacOS version?

AFAIK there were/are reports about problems with Big Sur in general...?

Correct me if I am wrong!

**Comment by osy** [comment]
Done: https://osy.gitbook.io/hac-mini-guide/post-installation/wifi

**Comment by Ikbosh** [comment]
Does this adapter have better bluetooth support for say AirPod pro's? Referring to the 16Khz/16-Bit

**Comment by keatliang2005** [comment]
anyone experience poor bluetooth range with BCM94352Z ??

with original intel bluetooth range can be quite far, i swap to this it have limited range.

i follow the color labeled.

![IMG_0153](https://user-images.githubusercontent.com/473990/114147974-dc25e500-994b-11eb-948c-8f56afdb15ff.jpg)

**Comment by Medizinmann-MD** [comment]
My range (using bluetooth headsets - Jabra Elite 75t and 65t) with the a card using BCMBCM94360NG is round about 5-10m - never tested the original Intel card though...
