### ISSUE TITLE
Usb disk failed

### ISSUE THREAD

**Issue by clicx** [osy/HaC-Mini#544]
I installed macos into usb disk and got works, however after installed the package, the disk can't boot, and as well as other windows based usb boot disk. 

I guess it caused by opencore, how can I reset uefi to original?

**Comment by osy** [comment]
Use your USB again and boot into the OC menu and select Reset NVRAM. Unplug the USB when the computer boots.

**Comment by clicx** [comment]
Hi Osy,

But the problem is seems I can't boot any USB disk, both macos installation disk and the disk that installed macos, and as well as Windows boot disk, only can boot windows which installed in local nvme ssd.

**Comment by clicx** [comment]
The boot menu show any usb disk as OpenCore, but nothing happen after select it to boot.

**Comment by clicx** [comment]
The boot menu show any usb disk as OpenCore, but nothing happen after select it to boot.

**Comment by osy** [comment]
Reset your bios.

**Comment by osy** [comment]
Anyways closing as this is not a support forum. Please check https://osy.gitbook.io/hac-mini-guide/post-installation/support for more info.
