### ISSUE TITLE
Hide Windows partition/disk through Boot Picker

### ISSUE THREAD

**Issue by mr-vito** [osy/HaC-Mini#551]
**Describe the bug**
When selecting Boot Picker during install, I am able to see the option to boot Windows installed on another SSD from OpenCore. I would like to remove this option from the Boot Picker and only show the HacMini partition/disk.

**Expected behavior**
OpenCore should not show the Windows partition/disk

**Configuration**
- HaC Mini version: 2.17
- OSX version: 11.2.2
- NUC model: NUC8i7HNK
- Boot SSD model and protocol: Crucial MX500 SATA 1TB (Windows only)
- Second SSD model and protocol (if installed): Crucial MX500 SATA 1TB (HacMini only)
- First DIMM model: Ballistix 2666Mhz 8GB 
- Second DIMM model (if installed): Ballistix 2666Mhz 8GB 
- Display port(s) used: HDMI
- Display resolution(s): 4K
- Any TB3 devices: No
- Any USB devices: No
- Any Wi-Fi/Bluetooth devices: Intel AC-9260

**Modifications**
N/A

**Panic log**
N/A

**Comment by osy** [comment]
I think you would have to manually modify your OC config.plist for this. It is too specific to support in the installer (since different people have different configurations).

**Comment by mr-vito** [comment]
Thanks osy!

Quick update for those interested in changing this behaviour.

Changing the ScanPolicy to failsafe value (17760515) will resolve the issue.

The default ScanPolicy is currently set to 0 through the Installer.

I can now see Big Sur volume, Recovery Disk and Reset NVRAM options only as desired.

I will report back if there are any issues when updating or reinstalling.
