### ISSUE TITLE
FAN sensor support

### ISSUE THREAD

**Issue by vit9696** [osy/HaC-Mini#553]
We were able to implement basic FAN sensor support for Intel NUCs in SMCSuperIO with @joedmru (https://github.com/acidanthera/VirtualSMC/commit/3b17b820271acef25560d0de6a9f9583874868cf). I believe this project might be willing to include this feature.

While all the monitoring registers are available in the source code, there are several limitations:
- voltages and temperatures are not exposed via SMC or I/O Registry.
- I/O Registry does not have accurate tachometer names.

Since neither of us owns a NUC and we are not much into remote debugging, I can suggest you to contribute a patch with a more complete support.

**Comment by osy** [comment]
@vit9696 Thanks will do. I've read through https://github.com/acidanthera/bugtracker/issues/395 and I am wondering where you got https://github.com/acidanthera/VirtualSMC/blob/master/Sensors/SMCSuperIO/ECDeviceNUC.hpp#L99-L110 from? Is it intentional that CPU and PCH temp offsets are the same?

**Comment by vit9696** [comment]
That's a typo, nice catch. The offsets are the result of a hard work over the evening :)

**Comment by osy** [comment]
I see, well it seems like you've done the hard work of finding the offsets. What do you need me to do?

**Comment by vit9696** [comment]
Well, basically I need you glue it nicely with the rest of the system, which is done much easier when you have the device.

* There are various temperature and voltage offsets, I'd like you expose them via I/O Registry just like we do for the other keys (with vendor-specific names).
* I'd also like you map these values to SMC keys (SMCSensorKeys.txt), so that more tools can see the sensors.
* Lastly, if you still are in the mood, you can try writing to this EC memory region and figure out how FAN control works. My source has no such thing. If you work it out it might be nice to have FAN control like in SMCDellSensors.

**Comment by profzei** [comment]
Must a question: is this work considered compatible oob also for other nucs like NUC7i3bnh?

**Comment by keatliang2005** [comment]
test the changes from 
https://github.com/osy/HaC-Mini/pull/555
will report if any anomalies.... 
![Screenshot 2021-03-29 at 8 30 05 PM](https://user-images.githubusercontent.com/473990/112836821-a7a16600-90cd-11eb-8973-4acf6985ff91.png)

**Comment by vit9696** [comment]
12V Main sounds like a bit too much. Can you also provide tests from https://github.com/crystalidea/macs-fan-control?

**Comment by vit9696** [comment]
Right, I can confirm this, this is `Power Supply voltage` or `DC In`. iStat is just borked.

**Comment by keatliang2005** [comment]
HWMSMC2
![Screenshot 2021-03-30 at 10 45 47 AM](https://user-images.githubusercontent.com/473990/112926023-6ba9e780-9145-11eb-8f41-195d39230d20.png)

MFC
![Screenshot 2021-03-30 at 10 47 37 AM](https://user-images.githubusercontent.com/473990/112926046-749ab900-9145-11eb-9eae-e8c83ff38e9f.png)

iStat only show one FAN avail. better then nothing 😂
![Screenshot 2021-03-30 at 10 50 54 AM](https://user-images.githubusercontent.com/473990/112926298-d3603280-9145-11eb-9860-1ba4d42437a6.png)

**Comment by profzei** [comment]
Hi, I'm using **Macs Fan Control** app over an Intel `NUC7i3BNH` + new `SMCSuperIO`: I followed instructions found in [EmbeddedControllers reference documentation for VirtualSMC](https://github.com/acidanthera/VirtualSMC/blob/master/Docs/EmbeddedControllers.md)

There is a warning about min value for RPM which is set as max RPM value... I think it could be useful report this here (even if Intel architecture is different!)...
![MacsFanControl-NUC7i3BNH](https://user-images.githubusercontent.com/47076961/113187465-2ecf1500-9259-11eb-8001-c69b9d315588.png)

**Comment by osy** [comment]
AFAIK that information doesn’t come from VirtualSMC (or VSMC doesn’t support the key for reading it).

**Comment by keatliang2005** [comment]
@vit9696 updated to Acidanthera Updates: April 2021

i suspect the virtual SMC somewhere broken, the fan speed monitoring broken

Follow EC doc
```
			<key>PciRoot(0x0)/Pci(0x1f,0x0)</key>
			<dict>
				<key>ec-device</key>
				<string>Intel_EC_V5</string>
				<key>model</key>
				<string>Intel Corporation Kaby Lake Series LPC Controller</string>
			</dict>

```

![Screenshot 2021-04-06 at 2 00 20 PM](https://user-images.githubusercontent.com/473990/113665661-73870000-96e0-11eb-82cd-14be8856f9eb.png)
![Screenshot 2021-04-06 at 1 59 59 PM](https://user-images.githubusercontent.com/473990/113665667-7681f080-96e0-11eb-9493-a8ad25c4a1b3.png)
![Screenshot 2021-04-06 at 1 58 31 PM](https://user-images.githubusercontent.com/473990/113665672-77b31d80-96e0-11eb-9a10-4339a27f05d5.png)

**Comment by vit9696** [comment]
Well, you should have tested intermediate builds. I believe I made no changes to @osy code though.

**Comment by keatliang2005** [comment]
i tested build from 

https://github.com/acidanthera/VirtualSMC/commit/a852b796325a23b3b5cac5540f26266b602073f4

until 

https://github.com/acidanthera/VirtualSMC/commit/747687f08986628181cade5227673bb16fd219b1

it works fine

specifically this https://github.com/acidanthera/VirtualSMC/commit/554b288efbf7770365612e99c00f225e9dfce496  build having issue shown

https://github.com/osy/HaC-Mini/issues/553#issuecomment-813846697

**Comment by vit9696** [comment]
Yeah, this is what @osy provided us with, very strange to be honest. I am quite sure he tested. Maybe some last minute modification had a regression somehow. I will let him debug.

**Comment by osy** [comment]
I’m out of town for two weeks but I did test it before and it was working fine. Can someone check if the other sensors (temp/voltage) work in ioreg?

**Comment by goodbest** [comment]
I have the same issue with @keatliang2005 

Fan speed shown in https://github.com/acidanthera/VirtualSMC/commit/747687f08986628181cade5227673bb16fd219b1
But always shows 0 for official 1.2.2 build. 

> Can someone check if the other sensors (temp/voltage) work in ioreg?
I can only see fan1 and fan2 sensor under LPCB@1F -> SMCSuperIO in ioreg.
Those sensors' values are real in build 747687,  but always 0 in official 1.2.2.
![image](https://user-images.githubusercontent.com/1118401/113724812-4f014700-9725-11eb-883f-92d85a33f66d.png)
![image](https://user-images.githubusercontent.com/1118401/113724830-532d6480-9725-11eb-963c-751fe06b82de.png)

**Comment by osy** [comment]
Hmm I suspect maybe there’s a bug in the generator or matching. Can someone try deleting all the resource plist for the NUC models except V5? Also try to revert each commit from my fork until it works again.

**Comment by profzei** [comment]
@osy @vit9696 
Similar issue for **NUC7i3BNH**
- using the attached version for `SMCSuperIO.kext`, taken from v. **1.2.2 beta  (I don't remember which commit**), I can see **only FAN0** which was **working** as reported [above](https://github.com/osy/HaC-Mini/issues/553#issuecomment-811282337) 
[SMCSuperIO.kext.zip](https://github.com/osy/HaC-Mini/files/6265319/SMCSuperIO.kext.zip)
- now, instead, using **official 1.2.2** version I can see two fans, **FAN1** and **FAN2**, both @ 0 rpms as you can see in the attached image from HWMonitorSMC2 v. 2.6.1
<img width="373" alt="Schermata 2021-04-06 alle 16 30 28" src="https://user-images.githubusercontent.com/47076961/113727444-6b858b00-96f5-11eb-947f-9ad8d178c19c.png">

**Comment by goodbest** [comment]
@osy maybe you shouldn't delete the following code `supportsMMIO = true;`
https://github.com/osy/VirtualSMC/commit/cdba325daeb2821464031e337dad34e03abce6c8#diff-1bd8a3b2b482cc7cbde219f5c0d27238ef3257e22603cdac071975d0ebb5d25dL300-L302
Which will cause the device won't initialize.


After the statement revert deletion, it all seems to work (except the value / 1000. May not be an issue for VSMC)

![image](https://user-images.githubusercontent.com/1118401/113886896-9bb35380-97f3-11eb-9df0-21565a05943e.png)

![image](https://user-images.githubusercontent.com/1118401/113886913-9fdf7100-97f3-11eb-83e4-5b4333d9d34c.png)

**Comment by osy** [comment]
Ah thanks for catching that!

**Comment by vit9696** [comment]
I imported the initial fix, as for values, I will let @osy handle it some time. Please confirm working.

**Comment by pierpaolodimarzo** [comment]
Hi guys,
I patched my NUC10i5, but the fans are not enabled; i used the latest version of kext .. would you have any solutions?

**Comment by osy** [comment]
I can confirm that @goodbest's fix works: https://github.com/osy/HaC-Mini/suites/2551855734/artifacts/55483215

**Comment by HorstBrack75** [comment]
> I can confirm that @goodbest's fix works: https://github.com/osy/HaC-Mini/suites/2551855734/artifacts/55483215

Hi osy, I would like to try the fix but the link seems not to be working.

**Comment by osy** [comment]
Are you logged in?

**Comment by HorstBrack75** [comment]
Sure, I couldn´t post a comment otherwise :-)

**Comment by keatliang2005** [comment]
Official kexts update works as planned.

**Comment by HorstBrack75** [comment]
Maybe I got this wrong or did not express myself correctly.

The .zip file from @goodbest fix seems corrupted.

I now installed 3.0.1 but the sensor range for the fans is still invalid.

<img width="732" alt="Screenshot 2021-05-14 at 09 00 02" src="https://user-images.githubusercontent.com/2854956/118234115-32c69780-b493-11eb-87e5-c66d6dafa4b2.png">

**Comment by keatliang2005** [comment]
> Maybe I got this wrong or did not express myself correctly.
> 
> The .zip file from @goodbest fix seems corrupted.
> 
> I now installed 3.0.1 but the sensor range for the fans is still invalid.
> 
> <img alt="Screenshot 2021-05-14 at 09 00 02" width="732" src="https://user-images.githubusercontent.com/2854956/118234115-32c69780-b493-11eb-87e5-c66d6dafa4b2.png">

the current sensor support only support reading the actual RPM value, as for range i don't think that is implemented

**Comment by LuckyLyz** [comment]
How can I deal with that issue ？> implemented

**Comment by nekkitl** [comment]
So, 2 years later and we still here. Hello everyone =]
