### ISSUE TITLE
iMessage not working

### ISSUE THREAD

**Issue by LiLCruz** [osy/HaC-Mini#554]
I did reset regenerate indentifiers no luck
![0FCE712C-8639-4D58-AE0D-3AE88D336B4B](https://user-images.githubusercontent.com/37666126/112766024-de984e80-8fdd-11eb-8779-7961ba82a52d.jpeg)

**Comment by osy** [comment]
You may have to reset identifiers and reinstall macos to clear anything that used the old indicators.

**Comment by LiLCruz** [comment]
Well I was on Mojave When that happened because I wanted use 32bit apps but I did reinstall Mac OS with clean install with Catalina gives me that same error And reset Indentifers still says same thing on catalina

**Comment by osy** [comment]
Can you try reset identifiers a couple more times?

**Comment by LiLCruz** [comment]
> Can you try reset identifiers a couple more times?

Ok will do will let you know change anything

**Comment by LiLCruz** [comment]
> Can you try reset identifiers a couple more times?

Tried it 10+ no luck getting it working says same thing

**Comment by Malumen** [comment]
I thought `iMessage` required proper WiFi device? Are you using a Broadcom WiFi card? If you enabled the `Itlwm.kext` feature, you are using an Intel based WiFi chip and that just allows WiFi access. I do not think it supports iMessage.

**Comment by osy** [comment]
Thanks @Malumen I did not know that.
