### ISSUE TITLE
Getting error when attempting to install Big Sur

### ISSUE THREAD

**Issue by StanKatsyuk** [osy/HaC-Mini#556]
**Describe the bug**
I am getting an error stating I should see support.apple.com/mac/startup. 

I am using a 128gb Micro SD card with default hacmini.pkg options. 

I have the latest (066) bios for my NUC. 

**Expected behavior**
I previously had Catalina installed so I'm expecting the install to work the same way as before. This morning I updated my bios, removed MacOS, installed ubuntu and started trying to install Big Sur.

**Environment:**
 - Running OSX version: none
 - Target drive OSX version: Big Sur
 - HaC Mini installer version: latest release as of today

**Additional context**
Images:
![PXL_20210330_054635964](https://user-images.githubusercontent.com/36254109/112941082-e392f600-90e2-11eb-9ba9-f3bb6bf32cb4.jpg)
![PXL_20210330_054933340](https://user-images.githubusercontent.com/36254109/112941087-e42b8c80-90e2-11eb-9bf0-7e7060d0b75a.jpg)

**Logs**
Please attach `/var/log/install.log` I don't have access to this as there is no OS I can get into to access terminal.

**Comment by osy** [comment]
Can you enable verbose boot by entering recovery mode and running `sudo nvram boot-args=“-v”` then take a picture of the error?

**Comment by StanKatsyuk** [comment]
@osy  Im not sure how to get into recovery mode. What im doing: 

1. Ive plugged in an Apple Magic Keyboard 2 and have it hardwired via USB
2. Powering on my NUC
3. Immediately pressing and holding CMD + R

I am still being taken to the install screen as I had shown in the images above

**Comment by osy** [comment]
You probably have to do it after OC loads but try this alternative way https://osy.gitbook.io/hac-mini-guide/post-installation/support#enable-verbose-boot

**Comment by StanKatsyuk** [comment]
@osy I tried the alternative way you suggested but still not able to get Big Sur to install. The only error message I can see is: 

<img width="645" alt="Screen Shot 2021-03-30 at 9 18 13 AM" src="https://user-images.githubusercontent.com/36254109/113021875-e1f41d00-9138-11eb-9346-e55f63a2421e.png">

Just for full transparency, the args I had selected from HacMini were: 
<img width="493" alt="Screen Shot 2021-03-30 at 9 04 15 AM" src="https://user-images.githubusercontent.com/36254109/113021951-f6381a00-9138-11eb-8e46-5befa19c534a.png">


thanks in advance

**Comment by osy** [comment]
I can only guess something is corrupted in your EFI partition. You can probably find help on various hackintosh forums or the r/hackintosh discord (we don’t provide support in this github). Worst case you can back up, completely wipe your hdd, and refollow the guide.

**Comment by StanKatsyuk** [comment]
@osy I think I got it working!

Looks like my 128GB MicroSD card was not working well. I used a 16GB Flash Drive connected to the USB C port on the front of the NUC and it seems to be installing.

**Comment by StanKatsyuk** [comment]
Thanks for all your help and all that you do!
