### ISSUE TITLE
Ultrafine 5K display issue with Thunderbolt legacy mode

### ISSUE THREAD

**Issue by fkpwolf** [osy/HaC-Mini#570]
In default/legacy mode, I can driver 5k display. But in MacOS, I can't find Ultrafine audio & camera devices. So looks Thunderblot USB didn't work. 
But if boot into Windows at first, then reboot to MacOS,  I can find all the USB devices. Looks Windows actived USB devices.

How can I use the basic USB functionality of Thunderblot in legacy mode?

**Comment by osy** [comment]
You can’t unfortunately. You need native mode.

**Comment by fkpwolf** [comment]
Good news: after upgraded BIOS to 66 version, everything works well in legacy mode, including audio & camera.
