### ISSUE TITLE
No sound output after upgrade to HacMini 3.1.1?

### ISSUE THREAD

**Issue by KrisCris** [osy/HaC-Mini#932]
**Describe the bug**
After upgrade from 3.0.1, both front and rear 3.5 headphone jacks stop outputting sound... system can't even recognize the rear jack when I plugged my headphone in.

**Expected behavior**
Sound output works

**Configuration**
- HaC Mini version [e.g: 2.0]: 3.1.1
- OSX version [e.g: 10.14.6]: 11.5.2
- NUC model [e.g: NUC8i7HNK]: HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: 
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: 
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: 
- Second DIMM model (if installed): 
- Display port(s) used [e.g: USB-C, mini DP]: 
- Display resolution(s) [e.g: 4K, 5K]: 
- Any TB3 devices: 
- Any USB devices: 
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: 

**Modifications**
No

**Panic log**
No

**Comment by KrisCris** [comment]
After rolled back to 3.0.1 audio come back

**Comment by osy** [comment]
@goodbest didn’t you find some issues with AppleALC

**Comment by goodbest** [comment]
Can you @KrisCris swap the following kexts one after another, and tell us which one works or not?
(you'd better use HacMini 3.1.1 at first)

2d777ea:
https://github.com/dortania/build-repo/releases/download/AppleALC-2d777ea/AppleALC-1.6.2-RELEASE.zip

9ce167f
https://github.com/dortania/build-repo/releases/download/AppleALC-9ce167f/AppleALC-1.6.4-RELEASE.zip

8daa5f3
https://github.com/dortania/build-repo/releases/download/AppleALC-8daa5f3/AppleALC-1.6.4-RELEASE.zip

**Comment by KrisCris** [comment]
After reinstall 3.1.1 with `reset boot-args` selected, issue fixed.
