### ISSUE TITLE
3.1.2 Losing Boot Device

### ISSUE THREAD

**Issue by fucongwanglucid** [osy/HaC-Mini#939]
**Describe the bug**
I upgraded to 3.1.2 from 3.0.1, and after the reboot, my boot device disappeared from the boot options. The system is 10.15.7.<br>
I reinstalled 10.15.7 using a recovery USB with 3.0.1 and it came back.<br>
I then installed 3.1.2 on the same recovery USB, wiped the hard drive and installed 10.15.7 from scratch, but the boot didn't come back. I tried resetting BIOS settings and NVRAM, but still it doesn't work.

**Expected behavior**
I expect that after I upgrade from 3.0.1 to 3.1.2, the system would boot up like usual.

**Configuration**
- HaC Mini version [e.g: 2.0]: 3.1.2
- OSX version [e.g: 10.14.6]: 10.15.7
- NUC model [e.g: NUC8i7HNK]: NUC8i7HVK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]: Samsung 970 Pro 512GB, NVMe
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: WD Blue 1TB, SATA
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: Kingston HyperX DDR4 16GB
- Second DIMM model (if installed): Kingston HyperX DDR4 16GB
- Display port(s) used [e.g: USB-C, mini DP]: mini DP
- Display resolution(s) [e.g: 4K, 5K]: 2K
- Any TB3 devices: No
- Any USB devices: Yes, Display as USB hub
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: BCM94360NG

**Modifications**
None

**Panic log**
Not available

**Comment by Przeblysk** [comment]
I installed V3.1.2 on a 10.15.7 system as well, same problem. Then I used USB to enter the system and re-tried to install V3.1.0 still could not boot properly, finally I had to return to V3.0.1 and then the system was normal.

**Comment by osy** [comment]
Is this the Bluetooth issue still?

**Comment by Przeblysk** [comment]
Using Broadcom's Bluetooth not Intel

**Comment by osy** [comment]
Those still running into the issue try reinstalling macos from the recovery partition.

**Comment by haiwitz** [comment]
Same issue with @fucongwanglucid & @Przeblysk .
Upgraded the EFI to 3.1.3 from 3.0.1, "macOS" and "Recovery 10.15.7" boot items both lost, Windows boots normally.
I remember I picked the "back up EFI" option, but I don't know where can I find the backup.
I'm using Dell DW1820A, separated 2 SSDs.
It's very appreciated if you could inform me the solution.

**Comment by osy** [comment]
@osy Can you try re-installing from a USB installer?

**Comment by VincentShin** [comment]
I got the same issue. Re-installing from a USB installer is no use.

**Comment by osy** [comment]
Can one of you in this thread with the issue try installing each version of HaC mini in reverse to find the first version that has this problem? That would help narrow down the issue.

**Comment by VincentShin** [comment]
I belive the first version has this problem is 3.1.0. The last workable version on my device is 3.0.1 which I still use now. I had try installing every version:3.1.0,3.1.1,3.1.2,3.1.3 for the past 3 months.
Information about my device is as same as the building-owner：NUC8i7HNK；MacOS 10.15.7 catalina

**Comment by osy** [comment]
One SSD or two? The SSD with macOS installed on is SATA or NVMe?

**Comment by VincentShin** [comment]
2 SSDs, one for windows, one for Mac. Both are NVMe PCI-E3.0 SSDs, Model is：
HIKVISION C2000pro 2TB（MacOS installed）
Asgard AN2 2TB（Windows10 installed）

**Comment by osy** [comment]
Okay I found the issue

https://github.com/acidanthera/OpenCorePkg/releases/tag/0.7.2

> Increased default APFS MinDate and MinVersion to macOS Big Sur for better security

I will release an update that will set the version back to the old values.

**Comment by Przeblysk** [comment]
1 SSD  WDS100T3X0C-00SJG0 PCI-Express

**Comment by VincentShin** [comment]
Very appreciated that！😊

**Comment by VincentShin** [comment]
Very appreciate that! 😊

**Comment by haiwitz** [comment]
Thank you for your work！

**Comment by VincentShin** [comment]
Nice！Problem solved！
