### ISSUE TITLE
Intel Bluetooth broken on macOS Monterey

### ISSUE THREAD

**Issue by mokapsing** [osy/HaC-Mini#942]
**PLEASE READ THE FOLLOWING**
* Make sure you installed the latest version of HaC Mini
* Follow **all** the [troubleshooting steps](https://osy.gitbook.io/hac-mini-guide/post-installation/support)
* Check the open issues and make sure it is not already reported
* Delete this section from your report and continue

**Describe the bug**
`I update my macos to Monterey RC2 from latest Big Sur with Hac-Mini v3.1.2, when it downloaded and preinstalled, it automatically restart, but it stuck in the loop, when I just see the Apple loading bar, it restart, then repeat again and again, I tried Reset NVRAM, but no use, now I can only enter Win11.`
**Expected behavior**
Monterey installed sucessfully
**Configuration**
- HaC Mini version [e.g: 2.0]:  `3.1.2`
- OSX version [e.g: 10.14.6]: `from lastest Big Sur to Monterey RC2`
- NUC model [e.g: NUC8i7HNK]: `NUC8i7HVK`
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]:  `Intel 760p 512GB`
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: `Intel 760p 512GB`
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: `Kingston HyperX DDR4 2666 8GB`
- Second DIMM model (if installed): `Kingston HyperX DDR4 2666 8GB`
- Display port(s) used [e.g: USB-C, mini DP]: `mini DP`
- Display resolution(s) [e.g: 4K, 5K]: `4K`
- Any TB3 devices: `none`
- Any USB devices: `keyboard and mouse`
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: `Original Intel card`
**Modifications**
List any mods to `config.plist`, any additional kexts, anything installed to `/Library/Extensions` and `/System/Library/Extensions`, any additional patches, etc. Please attach your `config.plist` if you made any modifications.
[config.plist.txt](https://github.com/osy/HaC-Mini/files/7405700/config.plist.txt)

![image](https://user-images.githubusercontent.com/39441028/138599918-f925fad4-aba7-44e4-98ed-86b4eeb36a3f.png)

**Panic log**
Include a screenshot of the panic message if applicable.

**Comment by khanhdt123** [comment]
> Does this work for you too @mokapsing and @khanhdt123

I am doing it! It work well

Thank all

**Comment by mokapsing** [comment]
> > > Does this work for you too @mokapsing and @khanhdt123
> > 
> > 
> > @osy @goodbest Restart loop now is gone. But the issue has not been solved completely, in the beginning, Bluetooth seems ok, it can connet to my Airpod, but after I turn off it, I can not turn on it, and it is on again after I restart the system, so I cannot manual turn on it once I turn it off.
> 
> try to reset NVRAM

I tried, but no help for me

**Comment by mokapsing** [comment]
> > > Does this work for you too @mokapsing and @khanhdt123
> > 
> > 
> > @osy @goodbest Restart loop now is gone. But the issue has not been solved completely, in the beginning, Bluetooth seems ok, it can connet to my Airpod, but after I turn off it, I can not turn on it, and it is on again after I restart the system, so I cannot manual turn on it once I turn it off.
> 
> try to reset NVRAM

@osy @goodbest now BT switch works well with the latest beta build of BlueToolFixup.kext
