### ISSUE TITLE
LAN2 broken on Monterey

### ISSUE THREAD

**Issue by andrewmed** [osy/HaC-Mini#947]
**Describe the bug**
LAN2 is not functioning on Monterey

**Expected behavior**
Should work. Also works on BigSur

**Configuration**
- HaC Mini version [e.g: 2.0]: v3.1.2
- OSX version [e.g: 10.14.6]: 15
- NUC model [e.g: NUC8i7HNK]: HVK
![IMG_0126](https://user-images.githubusercontent.com/13799337/139328296-f91024f6-1ac0-4c64-a064-a191f6ffdbc1.JPG)

![IMG_0125](https://user-images.githubusercontent.com/13799337/139328273-ef235b80-901d-40dd-b087-f9d40e5461e2.JPG)

**Comment by runninglol** [comment]
I got the same problem, only LAN1 works.

**Comment by goodbest** [comment]
We probability have to wait for upstream kext updating first, which sees no ETA.
https://github.com/khronokernel/SmallTree-I211-AT-patch/issues/3

**Comment by andrewmed** [comment]
So sorry to hear, my LAN1 is broken, so for me this is a dealbreaker
Will have to wait

**Comment by Littlehairs0925** [comment]
[AppleIGB_i210i211.kext.zip](https://github.com/osy/HaC-Mini/files/7452099/AppleIGB_i210i211.kext.zip)

**Comment by goodbest** [comment]
> So sorry to hear, my LAN1 is broken, so for me this is a dealbreaker
> Will have to wait

you can also use USB （both type A or C）to ethernet convertor.
There should be many ports available for this nuc

**Comment by nirh216** [comment]
> AppleIGB_i210i211.kext.zip

is this the LAN fix? 
Where should we put it?

Thanks@!

**Comment by nirh216** [comment]
Same issue with me.. 
LAN not working... both ports
OSX Monterey 12.0.1

**Comment by osy** [comment]
Small Tree Support says they are working on updating the drivers. We just have to wait on them.

**Comment by Medizinmann-MD** [comment]
Could AppleIGB be the solution?
https://github.com/khronokernel/SmallTree-I211-AT-patch/issues/3#issuecomment-1029787321
https://github.com/donatengit/AppleIGB

**Comment by alenzhong** [comment]
Replacing SmallTreeIntel82576.kext with AppleIGB.kext solves the problem。

**Comment by Lorys89** [comment]
@osy  @alenzhong  hello, you can try this version of the kext igb, if I'm not mistaken, mount the i210
[AppleIGB.kext.zip](https://github.com/osy/HaC-Mini/files/9950812/AppleIGB.kext.zip)

if it works and navigate send ioreg log
https://www.macos86.it/topic/6029-appleigb-and-intelmausi-integration/
i211 works fine, of i210 we have no evidence except one on trx40 gigabyte that doesn't work

**Comment by topiga** [comment]
> @osy @alenzhong hello, you can try this version of the kext igb, if I'm not mistaken, mount the i210 [AppleIGB.kext.zip](https://github.com/osy/HaC-Mini/files/9950812/AppleIGB.kext.zip)
> 
> if it works and navigate send ioreg log https://www.macos86.it/topic/6029-appleigb-and-intelmausi-integration/ i211 works fine, of i210 we have no evidence except one on trx40 gigabyte that doesn't work

Tested, works great.
[Archive.zip](https://github.com/osy/HaC-Mini/files/10758601/Archive.zip)
