### ISSUE TITLE
NUC8i7HVK can't be insallted any more

### ISSUE THREAD

**Issue by clicx** [osy/HaC-Mini#952]
**Describe the bug**
many days ago I have installed Catalina with successfully. But after a boot failure I can't install again.
When I boot from USB disk, it shows the partition to boot, after selected the USB drive, the boot menu shows correctly with Install Catalina and Reset NVRam. After select Install Catalina, windows go dark screen and reboot after a few seconds. I have tried many ways always the same problem.
And after the second boot, the bootmenu in the bios of USB drive shows as "OpenCore", so I think it related to the Opencore.

**Expected behavior**

**Environment:**
 - Running OSX version: macOS Cataina 10.15.7
 - Target drive OSX version: 
 - HaC Mini installer version: newest

**Additional context**

**Logs**
Please attach `/var/log/install.log`

**Comment by smounives** [comment]
I have the same issue. I have tried installing Big Sur and Monterey, both are normal, only Big Sur will repeatedly enter the USB drive Installer after reboot.

**Comment by clicx** [comment]
Hi smounives, is Big Sur working good on the hades?

**Comment by smounives** [comment]
> Hi smounives, is Big Sur working good on the hades?

yes

**Comment by x2358473** [comment]
I hope someone can fix it，Catalina has a better experience than Big Sur.

**Comment by Murphy41** [comment]
I have the same issue. The boot menu in the bios of the USB drive shows as "OpenCore" and it will get back to the boot menu every time after I chose "OpenCore". I've tried tapping or holding alt but still doesn't work.
