### ISSUE TITLE
macOS 12.1  SDXC

### ISSUE THREAD

**Issue by qwe123cjl** [osy/HaC-Mini#975]
Using hacmini 3.1.4 the card reader still doesn't work and doesn't show up, not usable

**Comment by thegass** [comment]
the built-in cardreader never worked for me.

**Comment by qwe123cjl** [comment]
> 内置的读卡器从来都不适合我。
Photographers need sdxc very much and the speed is not bad

**Comment by osy** [comment]
1. Does it work in Windows
2. Can you give the brand and model of the card

**Comment by qwe123cjl** [comment]
> 



> * Does it work in Windows
> * Does it work on macOS 10.15.X?
> * Can you give the brand and model of the card

SDXC works very well on any version of Windows, no problem with hot plugging

Works perfectly on macOS 10.15.x, same as Windows

The SD cards I use are SanDisk and Samsung
SanDisk 256g v30 170MB/S. samsung evo plus 128g

I have a lot of time now, you can ask me in time

**Comment by osy** [comment]
Can you try an older SDHC card?

**Comment by qwe123cjl** [comment]
> Can you try an older SDHC card?
Samsung evo plus 128g is a very old card, SanDisk didn't work in macOS 11.6.1, but Samsung's is working fine, now macOS 12.1 is not available, and there is no card reader in the system report Any information that this computer does not contain any Apple internal memory card reader

**Comment by osy** [comment]
So on 11.6.1 you have Samsung card working but SanDisk does not work. On 12.1, both cards do not work?

**Comment by qwe123cjl** [comment]
> So on 11.6.1 you have Samsung card working but SanDisk does not work. On 12.1, both cards do not work?

Yes, in macOS 12.1, no sd card will work

**Comment by qwe123cjl** [comment]
> 



> So on 11.6.1 you have Samsung card working but SanDisk does not work. On 12.1, both cards do not work?

I saw two hardware IDs in the new version of AppleSDXC.kext: pci17a0,9755 and pci14e4,16bc
I have tried changing the PCI address in config to
pci17a0,9755 The system report shows that it has been driven and can see the information of the card reader, but when I insert the sd card I own into the card reader, there is no sd card information on the computer, it cannot work and cannot be used

**Comment by Daasin** [comment]
Is there an update on this by any chance?

**Comment by Daasin** [comment]
@osy @qwe123cjl Was there an update on this by any chance?

**Comment by ishadowland** [comment]
Same issue here, SD card reader not woring on macos. I can see Internal SD card reader in system information, but nothing showup in disk utility or desktop.

![截屏2022-11-05 下午9 17 05](https://user-images.githubusercontent.com/69557008/200121815-3fd58106-8e08-42a3-bd19-9194ef4706cd.png)

I've tried different sdcard from sdandard  sd / SDHC to microsd with SD adapter. Nun of them works so far.

MacOS Version seems irrelevant nether. the issue appers the same from Mojave all the way up to Ventora 13.0.

p.s It Works fine on Windows10 12H2 (w/bootcamp).

**Comment by topiga** [comment]
See #1056
