### ISSUE TITLE
Black screen after updating to MacOS 12.1

### ISSUE THREAD

**Issue by VincentShin** [osy/HaC-Mini#981]
**Describe the bug**
I was update from 10.15.7 to 12.1 though the AppStore yesterday. I know it's sounds stupid. But it just happened.
The whole installation process looks great, but when I start up for the first time in MacOS 12.1, after the Apple logo and loading bar，black screen. Yes，the display has no respond. but I can hear the sound when i strike the keyboard. it's means the system is already start, but no picture! What can i do ??please help!
I was trying to install hacmini in USB to boot. but after booting process, display still not working.

**Configuration**
- HaC Mini version [3.1.4\3.1.3\3.1.2]: 
- OSX version [10.15.7 update to 12.1: 
- NUC model [ NUC8i7HNK]: 
- Boot SSD model and protocol [HIKVISION C2000pro 2TB（MacOS installed）]: 
- Second SSD model and protocol (if installed) [Asgard AN2 2TB（Windows10 installed）]: 
- First DIMM model [micron DDR4-3200 16GB]: 
- Second DIMM model (micron DDR4-3200 16GB): 
- Display port(s) used [mini DP、HDMI both have trid]: 
- Display resolution(s) [2K]: 
- Any TB3 devices: no
- Any USB devices: no
- Any Wi-Fi/Bluetooth devices [e.g:DW1820A, BCM94360CS2, Intel 8265]: no

**Comment by osy** [comment]
I haven't heard of this before but one thing I would try is to make sure the iGPU is disabled in bios. Another thing is to try another monitor in case there's some weird compatibility of your monitor with latest macos.

**Comment by VincentShin** [comment]
I have tried, disabled the iGPU, Change a 1080p monitor.But nothing's changed.

> I haven't heard of this before but one thing I would try is to make sure the iGPU is disabled in bios. Another thing is to try another monitor in case there's some weird compatibility of your monitor with latest macos.

**Comment by osy** [comment]
Can you confirm that: 1) you've installed 3.1.4 before updating and 2) updated to 12.1 NOT 12.3 beta?

**Comment by VincentShin** [comment]
1)Yes. 
2)To be honest, I can't remember. Considering that I upgraded the system directly from the App-store, It should be the latest version of MacOS right? I will not  able to confirm that in this circumstance.  BUT! I already tried a USB MacOS12.1 installer just now. It said I can't rollback the system version. So I think the version I had upgraded must later than the MacOS 12.1

> Can you confirm that: 1) you've installed 3.1.4 before updating and 2) updated to 12.1 NOT 12.3 beta?

**Comment by osy** [comment]
Can you look in your EFI partition for EFI/OC/Kexts/Polaris22Fixup.kext/Contents/Info.plist and list the CFBundleVersion.

**Comment by VincentShin** [comment]
Problem solved！I re-install macOS Monterey from recovery，and use the USB hacmini3.1.5 to boot in the Monterey!Very appreciate your work! You save my life again!! OSY YYDS!!!😊😊😊

> Can you look in your EFI partition for EFI/OC/Kexts/Polaris22Fixup.kext/Contents/Info.plist and list the CFBundleVersion.

**Comment by VincentShin** [comment]
a-oh, rest the nvram, and display not respond again. I'm cryiiiiiiiiiiing

**Comment by osy** [comment]
I suspect you didn't update HaC mini on your boot drive. If you installed it to a USB then only the usb is updated. Your boot drive is probably running an older version. Which is why I asked you to post your CFBundleVersion for Polaris22Fixup which you completely ignored...

**Comment by VincentShin** [comment]
I'm sorry,It's not a ignoration.in fact, As a none English native speaking person, every reply in here is difficult to me. I don't know what is this CFBundleVersion and Polaris22Fixup means.
And the good news is, everything runs perfectly now on my device. First, I press “Shift”  to boot in the safe mode of MacOS 12.2.1. Run the "time machine"to make my data backup. Then do a fresh install of MacOS 12.1,  using Hacmini 3.1.4 to boot in. Last, restore the"MacOS 12.2.1 time machine back up" in the MacOS 12.1. At this point, All problem solved.😊😊😊
Anyway, Very appreciate your work and patient reply!😊😊😊

**Comment by VincentShin** [comment]
My originally thinking is stay in MacOS 10.15.7 forever. But have bought the RX 6600xt eGPU recent days. So I must take the risk to update MacOS 12. Now the eGPU runs perfectly. It makes me very happy.😊😊😊

**Comment by osy** [comment]
Okay glad to see it works, closing.
