### ISSUE TITLE
Airplay to Mac disabled in 12.3

### ISSUE THREAD

**Issue by tangbonze** [osy/HaC-Mini#991]
Not sure you guys noticed, Airplay to Mac feature disabled after upgrade to 12.3 which is working fine before. 

I saw some workaround related to opencore legacy patcher which is used to force open unsupported features for old Mac.

I believe there are lots of differences between hacmini and mac. So, I came here to ask gently: Is there any workaround to crack open it for hacmini? 

Thanks in advance.

**Comment by goodbest** [comment]
Use the latest FeatureUnlock may help.
https://github.com/acidanthera/FeatureUnlock

**Comment by osy** [comment]
I can include this next update.

**Comment by tangbonze** [comment]
> 

Great to know. Thank you.

**Comment by tangbonze** [comment]
> Use the latest FeatureUnlock may help. https://github.com/acidanthera/FeatureUnlock

Thanks for your advice. I'm worried about mess up kext since I dont have much knowledge about it. I will wait for next release.
