### ISSUE TITLE
lg ultrafine 5k  Black screen, no display

### ISSUE THREAD

**Issue by tnwss** [osy/HaC-Mini#995]
bigsur 15.6 lg ultrafine 5k  Black screen, no display
windows  11 Same thing

**Comment by osy** [comment]
You did not provide the requested information when opening the issue. I suspect you did not install native thunderbolt correctly either because you did not select the option or you did not run the patcher. Please follow the guide.

**Comment by xiaooloong** [comment]
这机器只有 DP1.2，所以 5k 分辨率需要双 DP。所以要么你的显示器本身就是双 DP 输入支持的 5k，要么就是用雷电协议，因为雷电协议可以包含两路 DP。恰巧这个机器就是送了两路 DP 进雷电。

安装 pkg 时选择“原生雷电”，安装后运行 “Thunderbolt Patcher.app” 给雷电固件打补丁。打好补丁后关机断电 10 秒，重新插电开机就可以在“系统信息”里面看到雷电控制器了。然后使用雷电线缆连接显示器试一试。

刷雷电补丁会造成在 windows 下雷电不可用。因此如果你要回滚补丁，你需要在苹果系统下再次运行 “Thunderbolt Patcher.app”，选中又下角“Uninstall” 反向刷一次补丁。刷完后同样需要关机并断电 10 秒。

刷雷电固件有风险，注意不要在未完成之前关闭刷写程序，否则会造成雷电彻底坏掉，需要其他电脑用编程器救砖。

顺便，我记得 LG Ultrafine 5k 有新老两个版本，老版本刚出来的时候雷电主控只支持 DP1.2，所以需要在雷电里跑双路 DP。新版本雷电主控支持 DP1.4 和 USB-C DP Alt 模式了，遇到支持 DP1.4 的机器，理论上单路 DP1.4 也可以？可惜冥王峡谷不支持 DP1.4。

**Comment by tnwss** [comment]
@xiaooloong  可以留下您的联系方式帮我解决一下问题吗   我5k 接的雷电三  开机没有显示 必须要链接一个额外的显示器 才可以点亮 且5K显示器还只能进系统之后才能显示！我太需要帮忙了 ！

**Comment by tnwss** [comment]
@xiaooloong 这让我很难受呀 如果只用雷电3 作为显示器 那么我用oc引导双系统 开机之后都无法选择系统！只能是双显示器（hdmi） 在另外一个显示器上面做选择才可以进系统！是否可以采用传统雷电解决我所说的问题！

**Comment by xiaooloong** [comment]
> 是否可以采用传统雷电解决我所说的问题吗

没有具体操作过。不过我在不打雷电补丁，就是 windows 下可以用雷电的状态，冷启动进苹果系统。开机有 BIOS/UEFI 画面，有 OC画面，最后会卡在内核不停刷日志的阶段（我开了 -v 详细输出，不开 -v 的话应该是第一屏白苹果进度条吧）。

**Comment by tnwss** [comment]
@xiaooloong 也是头疼 现在开机必须两个显示器 ，5k显示不了引导  期望修复吧
